### ISSUE TITLE
SeatObserverMultiplexer uses ObserverMultiplexer, ThreadExecutor and owning pointers

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#112]
This:
```
void mi::SeatObserverMultiplexer::seat_dispatch_event(
    std::shared_ptr<MirEvent const> const& event)
{
    for_each_observer(&mi::SeatObserver::seat_dispatch_event, event);
}
```
Uses this:
```
template<class Observer>
template<typename MemberFn, typename... Args>
void ObserverMultiplexer<Observer>::for_each_observer(MemberFn f, Args&&... args)
{
    static_assert(
        std::is_member_function_pointer<MemberFn>::value,
        "f must be of type (Observer::*)(Args...), a pointer to an Observer member function.");
    auto const invokable_mem_fn = std::mem_fn(f);
    std::shared_lock<decltype(observer_mutex)> lock{observer_mutex};
    for (auto& observer_pair: observers)
    {
        if (auto observer = observer_pair.second.lock())
        {
            observer_pair.first.spawn(std::bind(invokable_mem_fn, observer.get(), std::forward<Args>(args)...));
        }
    }
}
```
Which results in a std::shared_ptr<MirEvent const> being held by the work supplied to the ThreadExecutor instance.

Occasionally, when the server shuts down this leads to a SEGFAULT:
```
#0  0x00007f9adeee535c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x7f9acc00ee40)
    at /usr/include/c++/6/bits/shared_ptr_base.h:150
#1  0x00007f9adeee500b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() (this=0x7f9acc00f178, __in_chrg=<optimised out>) at /usr/include/c++/6/bits/shared_ptr_base.h:662
#2  0x00007f9adef96c0a in std::__shared_ptr<MirEvent const, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() (this=0x7f9acc00f170, __in_chrg=<optimised out>) at /usr/include/c++/6/bits/shared_ptr_base.h:928
#3  0x00007f9adef96c26 in std::shared_ptr<MirEvent const>::~shared_ptr() (this=0x7f9acc00f170, __in_chrg=<optimised out>)
    at /usr/include/c++/6/bits/shared_ptr.h:93
#4  0x00007f9adefb96f8 in std::_Head_base<1ul, std::shared_ptr<MirEvent const>, false>::~_Head_base() (this=0x7f9acc00f170, __in_chrg=<optimised out>) at /usr/include/c++/6/tuple:102
#5  0x00007f9adefb9714 in std::_Tuple_impl<1ul, std::shared_ptr<MirEvent const> >::~_Tuple_impl() (this=0x7f9acc00f170, __in_chrg=<optimised out>) at /usr/include/c++/6/tuple:338
#6  0x00007f9adefb9730 in std::_Tuple_impl<0ul, mir::input::SeatObserver*, std::shared_ptr<MirEvent const> >::~_Tuple_impl() (this=0x7f9acc00f170, __in_chrg=<optimised out>) at /usr/include/c++/6/tuple:180
#7  0x00007f9adefb974c in std::tuple<mir::input::SeatObserver*, std::shared_ptr<MirEvent const> >::~tuple() (this=0x7f9acc00f170, __in_chrg=<optimised out>) at /usr/include/c++/6/tuple:866
#8  0x00007f9adefb976c in std::_Bind<std::_Mem_fn<void (mir::input::SeatObserver::*)(std::shared_ptr<MirEvent const> const&)> (mir::input::SeatObserver*, std::shared_ptr<MirEvent const>)>::~_Bind() (this=0x7f9acc00f160, __in_chrg=<optimised out>) at /usr/include/c++/6/functional:918
#9  0x00007f9adefbe6c6 in std::_Function_base::_Base_manager<std::_Bind<std::_Mem_fn<void (mir::input::SeatObserver::*)(std::shared_ptr<MirEvent const> const&)> (mir::input::SeatObserver*, std::shared_ptr<MirEvent const>)> >::_M_destroy(std::_Any_data&, std::integral_constant<bool, false>) (__victim=...) at /usr/include/c++/6/functional:1586
#10 0x00007f9adefbd170 in std::_Function_base::_Base_manager<std::_Bind<std::_Mem_fn<void (mir::input::SeatObserver::*)(std::shared_ptr<MirEvent const> const&)> (mir::input::SeatObserver*, std::shared_ptr<MirEvent const>)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation) (__dest=..., __source=..., __op=std::__destroy_functor)
    at /usr/include/c++/6/functional:1610
#11 0x00007f9adeee4d05 in std::_Function_base::~_Function_base() (this=0x7f9acc011418, __in_chrg=<optimised out>)
    at /usr/include/c++/6/functional:1690
#12 0x00007f9adeee9ee6 in std::function<void ()>::~function() (this=0x7f9acc011418, __in_chrg=<optimised out>)
    at /usr/include/c++/6/functional:1834
#13 0x00007f9adef04610 in mir::GLibMainLoop::<lambda()>::~<lambda>(void) (this=0x7f9acc011410, __in_chrg=<optimised out>)
    at /home/alan/display_server/mir/src/server/glib_main_loop.cpp:401
#14 0x00007f9adef07fe4 in std::_Function_base::_Base_manager<mir::GLibMainLoop::spawn(std::function<void()>&&)::<lambda()> >::_M_destroy(std::_Any_data &, std::false_type) (__victim=...) at /usr/include/c++/6/functional:1586
#15 0x00007f9adef06b87 in std::_Function_base::_Base_manager<mir::GLibMainLoop::spawn(std::function<void()>&&)::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=std::__destroy_functor) at /usr/include/c++/6/functional:1610
#16 0x00007f9adeee4d05 in std::_Function_base::~_Function_base() (this=0x7f9acc0de808, __in_chrg=<optimised out>)

```

**Comment by AlanGriffiths** [comment]
I've an "ignorant" solution here: https://github.com/MirServer/mir/tree/dont-queue-owning-pointers-on-long-lived-executor-part2

But I don't like it as it will lose notifications for any events that don't live long enough.

OTOH If these events *are* worth reporting in detail, maybe we should extract the detail and report that, not hold onto the events.
