### ISSUE TITLE
[miral-shell] Hangs on exit when run with multiple X11 windows

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1327]
```plain
miral-app --x11-output 640x480:640x480
```
Hit `Ctrl-Alt-BkSp` to exit.

Expect: both windows close
Actual: Both windows go black and keyboard input remains grabbed.

**Comment by AlanGriffiths** [comment]
This is a problem with the "spinner". I have the following stacktrace:

```plain
#3  0x00005555555d4a05 in MirEglSurface::MirEglSurface(std::shared_ptr<MirEglApp> const&, wl_output*, int, int) (this=0x7fffbc2b0ce0, mir
_egl_app=std::shared_ptr<MirEglApp> (use count 2, weak count 0) = {...}, wl_output=0x7fffbc005dc0, width_=640, height_=480)
    at /home/alan/display_server/mir/examples/miral-shell/spinner/miregl.cpp:245
#4  0x00005555555d7fb0 in __gnu_cxx::new_allocator<MirEglSurface>::construct<MirEglSurface, std::shared_ptr<MirEglApp> const&, wl_output*
 const&, int const&, int const&>(MirEglSurface*, std::shared_ptr<MirEglApp> const&, wl_output* const&, int const&, int const&) (this=0x7f
ffd97f9677, __p=0x7fffbc2b0ce0, __args#0=std::shared_ptr<MirEglApp> (use count 2, weak count 0) = {...}, __args#1=@0x7fffbc005ec0: 0x7fff
bc005dc0, __args#2=@0x7fffbc005ed0: 640, __args#3=@0x7fffbc005ed4: 480) at /usr/include/c++/7/ext/new_allocator.h:136
#5  0x00005555555d7c12 in std::allocator_traits<std::allocator<MirEglSurface> >::construct<MirEglSurface, std::shared_ptr<MirEglApp> cons
t&, wl_output* const&, int const&, int const&>(std::allocator<MirEglSurface>&, MirEglSurface*, std::shared_ptr<MirEglApp> const&, wl_outp
ut* const&, int const&, int const&) (__a=..., __p=0x7fffbc2b0ce0, __args#0=std::shared_ptr<MirEglApp> (use count 2, weak count 0) = {...}
, __args#1=@0x7fffbc005ec0: 0x7fffbc005dc0, __args#2=@0x7fffbc005ed0: 640, __args#3=@0x7fffbc005ed4: 480)
    at /usr/include/c++/7/bits/alloc_traits.h:475
#6  0x00005555555d77e3 in std::_Sp_counted_ptr_inplace<MirEglSurface, std::allocator<MirEglSurface>, (__gnu_cxx::_Lock_policy)2>::_Sp_cou
nted_ptr_inplace<std::shared_ptr<MirEglApp> const&, wl_output* const&, int const&, int const&>(std::allocator<MirEglSurface>, std::shared
_ptr<MirEglApp> const&, wl_output* const&, int const&, int const&) (this=0x7fffbc2b0cd0, __a=...)
    at /usr/include/c++/7/bits/shared_ptr_base.h:526
#7  0x00005555555d70ee in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<MirEglSurface, std::allocator<MirEglSurface>, s
td::shared_ptr<MirEglApp> const&, wl_output* const&, int const&, int const&>(std::_Sp_make_shared_tag, MirEglSurface*, std::allocator<Mir
EglSurface> const&, std::shared_ptr<MirEglApp> const&, wl_output* const&, int const&, int const&) (this=0x7fffd97f9918, __a=...)
    at /usr/include/c++/7/bits/shared_ptr_base.h:637
#8  0x00005555555d69a9 in std::__shared_ptr<MirEglSurface, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<MirEglSurface>, std::
```

By way of confirmation the corresponding mir_demo_server invocation does not have a problem.
