### ISSUE TITLE
On Fedora rawhide mir_acceptance_test hangs (sometimes)

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1399]
Caught it once: it's been on the same line for over an hour:

```plain
#0  0x00007f3c0258d5bc in read () at /lib64/libpthread.so.0
#1  0x0000000001070144 in ServerStartupReliability_can_start_with_low_entropy_Test::TestBody() (this=0x3294660) at /home/alan/mir/tests/acceptance-tests/test_server_startup.cpp:79
```
It's the `while` loop here:
```c++
    // Flush the entropy pool
    int fd = open("/dev/random", O_RDONLY | O_NONBLOCK);
    ASSERT_THAT(fd, Ge(0));
    char buf[256];
    while (read(fd, buf, sizeof buf) > 0) {}
    close(fd);
```
I guess we're failing to "flush the entropy pool". (It's a pretty inelegant approach.)

**Comment by AlanGriffiths** [comment]
We have similar code in mir_unit_tests:
```c++
void drain_dev_random()
{
    // Flush the entropy pool
    int fd = open("/dev/random", O_RDONLY | O_NONBLOCK);
    ASSERT_THAT(fd, ::testing::Ge(0));
    char buf[256];
    while (read(fd, buf, sizeof buf) > 0) {}
    close(fd);
}
```
That likely has the same issue.
