### ISSUE TITLE
Clients can crash our wayland implementation

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#149]
This is the interesting bit of the WAYLAND_DEBUG trace from the client:

```
[708998.987]  -> wl_surface@25.attach(nil, 0, 0)
[708999.051]  -> wl_surface@25.commit()
```

This is the stack trace from the server:

```
(gdb) bt
#0  0x00007ffff3001c7c in  () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#1  0x00007ffff2ffd054 in wl_resource_instance_of () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#2  0x00007ffff2ffea7c in wl_shm_buffer_get () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#3  0x00007ffff5c2ad83 in mir::frontend::WlSurface::commit() (this=0x7fffc8147550)
    at /home/alan/MirServer/mir/src/server/frontend/wayland/wayland_connector.cpp:425
#4  0x00007ffff5c358bd in mir::frontend::wayland::Surface::commit_thunk(wl_client*, wl_resource*) (resource=0x7fffc813c380) at /home/alan/MirServer/mir/src/server/frontend/wayland/core_generated_interfaces.h:1164
#5  0x00007ffff0acfe18 in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#6  0x00007ffff0acf87a in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#7  0x00007ffff30011fe in  () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#8  0x00007ffff2ffd3f7 in  () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#9  0x00007ffff2fff472 in wl_event_loop_dispatch () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#10 0x00007ffff2ffd91a in wl_display_run () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#11 0x00007ffff5c5b1e2 in std::_Bind_simple<void (*(wl_display*))(wl_display*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0xfcb818) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1390
#12 0x00007ffff5c5b195 in std::_Bind_simple<void (*(wl_display*))(wl_display*)>::operator()() (this=0xfcb818)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1380
#13 0x00007ffff5c5af69 in std::thread::_State_impl<std::_Bind_simple<void (*(wl_display*))(wl_display*)> >::_M_run() (this=0xfcb810) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/thread:197
#14 0x00007ffff680c83f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007ffff525e6da in start_thread (arg=0x7fffe77fe700) at pthread_create.c:456
#16 0x00007ffff627bd7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

Encountered on 17.04 (I know) + trunk.

$ WAYLAND_DEBUG=1 MIR_EXPERIMENTAL_XDG_SHELL=1 cmake-build-debug/bin/miral-shell
$ WAYLAND_DEBUG=1 QT_QPA_PLATFORM=WAYLAND kate

Select File, Open

**Comment by RAOF** [comment]
Don't know why that didn't autoclose. Anyway…
