### ISSUE TITLE
Crash in wl_resource_post_event on shutdown

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1492]
So far I've only observed this when there are lots of X11 windows open, and only in versions of Mir a few months back (since more recent Mir crashes when too many X11 windows are opened, this isn't surprising).

Destroying the `wl_client` is destroying all resources, including surfaces. It looks like the `wl_surface`  with the pointer over it is getting destoryed before the `wl_pointer`, which is causeing `WlPointer::leave()` to get called. This is sending a leave event with the surface's wl_resource, which is failing because `resource->object.interface` is currupted, presumably because the resource is in the process of being freed. I don't know why the resource is destroyed before the `WlSurface` destructor is done, or why most of the time this works fine.

Stack trace:
```
(gdb) bt full
#0  0x00007ffff6292948 in wl_resource_post_event (resource=0x7fffb4025f60, opcode=1) at src/wayland-server.c:249
        args = 
            {{i = -1270106996, u = 3024860300, f = -1270106996, s = 0x7fffb44bb48c "", o = 0x7fffb44bb48c, n = 3024860300, a = 0x7fffb44bb48c, h = -1270106996}, {i = -1274857088, u = 3020110208, f = -1274857088, s = 0x7fffb4033980 "ȏ`\367\377\177", o = 0x7fffb4033980, n = 3020110208, a = 0x7fffb4033980, h = -1274857088}, {i = -1082141184, u = 3212826112, f = -1082141184, s = 0x7fffbf7fd600 "", o = 0x7fffbf7fd600, n = 3212826112, a = 0x7fffbf7fd600, h = -1082141184}, {i = -150874070, u = 4144093226, f = -150874070, s = 0x7ffff701d82a <mir::scene::ApplicationSession::destroy_buffer_stream(std::shared_ptr<mir::frontend::BufferStream> const&)> "UH\211\345ATSH\203\354`H\211}\230H\211u\220dH\213\004%(", o = 0x7ffff701d82a <mir::scene::ApplicationSession::destroy_buffer_stream(std::shared_ptr<mir::frontend::BufferStream> const&)>, n = 4144093226, a = 0x7ffff701d82a <mir::scene::ApplicationSession::destroy_buffer_stream(std::shared_ptr<mir::frontend::BufferStream> const&)>, h = -150874070}, {i = 0, u = 0, f = 0, s = 0x0, o = 0x0, n = 0, a = 0x0, h = 0}, {i = 1433671744, u = 1433671744, f = 1433671744, s = 0x555555741840 "\023", o = 0x555555741840, n = 1433671744, a = 0x555555741840, h = 1433671744}, {i = -1082136832, u = 3212830464, f = -1082136832, s = 0x7fffbf7fe700 "", o = 0x7fffbf7fe700, n = 3212830464, a = 0x7fffbf7fe700, h = -1082136832}, {i = -149136558, u = 4145830738, f = -149136558, s = 0x7ffff71c5b52 <__gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<mir::frontend::WlSurfaceState::Callback, std::allocator<mir::frontend::WlSurfaceState::Callback>, (__gnu_cxx::_Lock_policy)2> >::deallocate(std::_Sp_counted_ptr_inplace<mir::frontend::WlSurfaceState::Callback, std::allocator<mir::frontend::WlSurfaceState::Callback>, (__gnu_cxx::_Lock_policy)2>*, unsigned long)+56> "\220\311ÐUH\211\345H\203\354\020H\211}\370H\211u\360H\213U\360H\213E\370H\211\326H\211\307\350\263\365\377\377\220\311\303UH\211\345AUATSH\203\354(H\211}\330H\211u\320H\211U\310H\213E\310H\211\307\350\271b\374\377L\213(H\213]\320H\211\336\277(", o = 0x7ffff71c5b52 <__gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<mir::frontend::WlSurfaceState::Callback, std::allocator<mir::frontend::WlSurfaceState::Callback>, (__gnu_cxx::_Lock_policy)2> >::deallocate(std::_Sp_counted_ptr_inplace<mir::frontend::WlSurfaceState::Callback, std::allocator<mir::frontend::WlSurfaceState::Callback>, (__gnu_cxx::_Lock_policy)2>*, unsigned long)+56>, n = 4145830738, a = 0x7ffff71c5b52 <__gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<mir::frontend::WlSurfaceState::Callback, std::allocator<mir::frontend::WlSurfaceState::Callback>, (__gnu_cxx::_Lock_policy)2> >::deallocate(std::_Sp_counted_ptr_inplace<mir::frontend::WlSurfaceState::Callback, std::allocator<mir::frontend::WlSurfaceState::Callback>, (__gnu_cxx::_Lock_policy)2>*, unsigned long)+56>, h = -149136558}, {i = -1269165880, u = 3025801416, f = -1269165880, s = 0x7fffb45a10c8 "\001", o = 0x7fffb45a10c8, n = 3025801416, a = 0x7fffb45a10c8, h = -1269165880}, {i = -1082141112, u = 3212826184, f = -1082141112, s = 0x7fffbf7fd648 "", o = 0x7fffbf7fd648, n = 3212826184, a = 0x7fffbf7fd648, h = -1082141112}, {i = -1082141152, u = 3212826144, f = -1082141152, s = 0x7fffbf7fd620 "@\326\177\277\377\177", o = 0x7fffbf7fd620, n = 3212826144, a = 0x7fffbf7fd620, h = -1082141152}, {i = -149143476, u = 4145823820, f = -149143476, s = 0x7ffff71c404c <std::pair<std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >, std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > > >::pair<std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >, std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >, true>(std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >&&, std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >&&)+54> "H\213U\370H\213", o = 0x7ffff71c404c <std::pair<std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >, std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > > >::pair<std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >, std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >, true>(std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >&&, std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >&&)+54>, n = 4145823820, a = 0x7ffff71c404c <std::pair<std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >, std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > > >::pair<std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >, std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >, true>(std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >&&, std::_Rb_tree_iterator<std::pair<void const* const, std::function<void ()> > >&&)+54>, h = -149143476}, {i = 0, u = 0, f = 0, s = 0x0, o = 0x0, n = 0, a = 0x0, h = 0}, {i = -1269173912, u = 3025793384, f = -1269173912, s = 0x7fffb459f168 "", o = 0x7fffb459f168, n = 3025793384, a = 0x7fffb459f168, h = -1269173912}, {i = -1082141120, u = 3212826176, f = -1082141120, s = 0x7fffbf7fd640 "\240\326\177\277\377\177", o = 0x7fffbf7fd640, n = 3212826176, a = 0x7fffbf7fd640, h = -1082141120}, {i = -1269173904, u = 3025793392, f = -1269173904, s = 0x7fffb459f170 "", o = 0x7fffb459f170, n = 3025793392, a = 0x7fffb459f170, h = -1269173904}, {i = -1082141120, u = 3212826176, f = -1082141120, s = 0x7fffbf7fd640 "\240\326\177\277\377\177", o = 0x7fffbf7fd640, n = 3212826176, a = 0x7fffbf7fd640, h = -1082141120}, {i = -149157330, u = 4145809966, f = -149157330, s = 0x7ffff71c0a2e <std::_Rb_tree<void const*, std::pair<void const* const, std::function<void ()> >, std::_Select1st<std::pair<void const* const, std::function<void ()> > >, std::less<void const*>, std::allocator<std::pair<void const* const, std::function<void ()> > > >::clear()+58> "\220\311ÐUH\211\345H\203\354 H\211}\350dH\213\004%(", o = 0x7ffff71c0a2e <std::_Rb_tree<void const*, std::pair<void const* const, std::function<void ()> >, std::_Select1st<std::pair<void const* const, std::function<void ()> > >, std::less<void const*>, std::allocator<std::pair<void const* const, std::function<void ()> > > >::clear()+58>, n = 4145809966, a = 0x7ffff71c0a2e <std::_Rb_tree<void const*, std::pair<void const* const, std::function<void ()> >, std::_Select1st<std::pair<void const* const, std::function<void ()> > >, std::less<void const*>, std::allocator<std::pair<void const* const, std::function<void ()> > > >::clear()+58>, h = -149157330}, {i = -1082141040, u = 3212826256, f = -1082141040, s = 0x7fffbf7fd690 "p\361Y\264\377\177", o = 0x7fffbf7fd690, n = 3212826256, a = 0x7fffbf7fd690, h = -1082141040}, {i = -1269173912, u = 3025793384, f = -1269173912, s = 0x7fffb459f168 "", o = 0x7fffb459f168, n = 3025793384, a = 0x7fffb459f168, h = -1269173912}}
        object = 0x7fffb4025f60
        ap = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffbf7fd720, reg_save_area = 0x7fffbf7fd650}}
#1  0x00007ffff66a6d08 in mir::wayland::Pointer::send_leave_event(unsigned int, wl_resource*) const (this=0x7fffb40255a0, serial=1565, surface=0x7fffb459f1b0)
    at /home/wmww/code/mir/src/wayland/generated/wayland_wrapper.cpp:2087
#2  0x00007ffff71dcc2c in mir::frontend::WlPointer::leave() (this=0x7fffb40255a0) at /home/wmww/code/mir/src/server/frontend_wayland/wl_pointer.cpp:162
        serial = 1565
#3  0x00007ffff71dc9f5 in operator()() const (__closure=0x7fffbf7fd898) at /home/wmww/code/mir/src/server/frontend_wayland/wl_pointer.cpp:151
        this = 0x7fffb40255a0
--Type <RET> for more, q to quit, c to continue without paging--
        serial = 32767
        final = {position = {x = {value = -1082140800}, y = {value = 32767}}, surface = 0x7ffff71dcc2c <mir::frontend::WlPointer::leave()+136>, is_in_input_region = 144}
#4  0x00007ffff71df320 in std::__invoke_impl<void, mir::frontend::WlPointer::enter(mir::frontend::WlSurface*, const mir::geometry::Point&)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...)
    at /usr/include/c++/10.1.0/bits/invoke.h:60
#5  0x00007ffff71dec03 in std::__invoke_r<void, mir::frontend::WlPointer::enter(mir::frontend::WlSurface*, const mir::geometry::Point&)::<lambda()>&>(struct {...} &) (__fn=...)
    at /usr/include/c++/10.1.0/bits/invoke.h:153
#6  0x00007ffff71de388 in std::_Function_handler<void(), mir::frontend::WlPointer::enter(mir::frontend::WlSurface*, const mir::geometry::Point&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/10.1.0/bits/std_function.h:291
#7  0x00007ffff6f37cfc in std::function<void ()>::operator()() const (this=0x7fffbf7fd898) at /usr/include/c++/10.1.0/bits/std_function.h:622
#8  0x00007ffff71bb34e in mir::frontend::WlSurface::~WlSurface() (this=0x7fffb459bb60, __in_chrg=<optimized out>) at /home/wmww/code/mir/src/server/frontend_wayland/wl_surface.cpp:110
        listener = 
            {first = 0x7fffb40255a0, second = {<std::_Maybe_unary_or_binary_function<void>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x7fffb40255a0, _M_const_object = 0x7fffb40255a0, _M_function_pointer = 0x7fffb40255a0, _M_member_pointer = (void (std::_Undefined_class::*)(class std::_Undefined_class * const)) 0x7fffb40255a0}, _M_pod_data = "\240U\002\264\377\177\000\000\000\000\000\000\000\000\000"}, _M_manager = 0x7ffff71de38b <std::_Function_handler<void(), mir::frontend::WlPointer::enter(mir::frontend::WlSurface*, const mir::geometry::Point&)::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>}, _M_invoker = 0x7ffff71de368 <std::_Function_handler<void(), mir::frontend::WlPointer::enter(mir::frontend::WlSurface*, const mir::geometry::Point&)::<lambda()> >::_M_invoke(const std::_Any_data &)>}}
        __for_range = Python Exception <class 'gdb.error'> Attempt to dereference a generic pointer.: 
std::map with 1 element
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
        __for_begin = {_M_node = 0x7fffb8044500}
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
        __for_end = {_M_node = 0x7fffbf7fd868}
Python Exception <class 'gdb.error'> Attempt to dereference a generic pointer.: 
        listeners = std::map with 1 element
#9  0x00007ffff71bb514 in mir::frontend::WlSurface::~WlSurface() (this=0x7fffb459bb60, __in_chrg=<optimized out>) at /home/wmww/code/mir/src/server/frontend_wayland/wl_surface.cpp:115
#10 0x00007ffff66aab12 in mir::wayland::Surface::Thunks::resource_destroyed_thunk(wl_resource*) (resource=0x7fffb45b5bb0) at /home/wmww/code/mir/src/wayland/generated/wayland_wrapper.cpp:1716
#11 0x00007ffff62927e0 in destroy_resource (element=0x7fffb45b5bb0, data=<optimized out>, flags=0) at src/wayland-server.c:724
        resource = 0x7fffb45b5bb0
#12 0x00007ffff6298b21 in for_each_helper (func=func@entry=0x7ffff6292780 <destroy_resource>, data=data@entry=0x7fffbf7fd9a4, entries=0x7fffb400e590, entries=<optimized out>) at src/wayland-util.c:372
        start = <optimized out>
        end = 0x7fffb8046970
        p = 0x7fffb80468f0
        ret = WL_ITERATOR_CONTINUE
#13 0x00007ffff6299030 in wl_map_for_each (map=map@entry=0x7fffb400e590, func=func@entry=0x7ffff6292780 <destroy_resource>, data=data@entry=0x7fffbf7fd9a4) at src/wayland-util.c:385
        ret = <optimized out>
#14 0x00007ffff629329e in wl_client_destroy (client=0x7fffb400e560) at src/wayland-server.c:883
        serial = 0
#15 0x00007ffff6293389 in destroy_client_with_error (reason=<optimized out>, client=<optimized out>) at src/wayland-server.c:319
        client = 0x7fffb400e560
        connection = <optimized out>
        resource = <optimized out>
        object = <optimized out>
        closure = <optimized out>
        message = <optimized out>
        p = {1, 786432}
        resource_flags = <optimized out>
        opcode = <optimized out>
        size = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        since = <optimized out>
        len = <optimized out>
#16 wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x7fffb400e560) at src/wayland-server.c:342
        client = 0x7fffb400e560
        connection = <optimized out>
        resource = <optimized out>
        object = <optimized out>
        closure = <optimized out>
        message = <optimized out>
        p = {1, 786432}
        resource_flags = <optimized out>
        opcode = <optimized out>
        size = <optimized out>
        since = <optimized out>
        len = <optimized out>
#17 0x00007ffff629605a in wl_event_loop_dispatch (loop=0x555555741840, timeout=timeout@entry=-1) at src/event-loop.c:1027
        ep = 
              {{events = 17, data = {ptr = 0x7fffb400f1f0, fd = -1275006480, u32 = 3019960816, u64 = 140736213348848}}, {events = 1, data = {ptr = 0x7fffb400f1f0, fd = -1275006480, u32 = 3019960816, u64 = 140736213348848}}, {events = 3133429504, data = {ptr = 0x3115c1ba, fd = 823509434, u32 = 823509434, u64 = 823509434}}, {events = 0, data = {ptr = 0x7fffb40074a0, fd = -1275038560, u32 = 3019928736, u64 = 140736213316768}}, {events = 3212827392, data = {ptr = 0x2400007fff, fd = 32767, u32 = 32767, u64 = 154618855423}}, {events = 0, data = {ptr = 0x7fffb400a4b8, fd = -1275026248, u32 = 3019941048, u64 = 140736213329080}}, {events = 3019932840, data = {ptr = 0xbf7fdb4000007fff, fd = 32767, u32 = 32767, u64 = 13798988851210911743}}, {events = 32767, data = {ptr = 0x7ffff62967c9 <wl_connection_flush+297>, fd = -165058615, u32 = 4129908681, u64 = 140737323296713}}, {events = 0, data = {ptr = 0x2400000000, fd = 0, u32 = 0, u64 = 154618822656}}, {events = 0, data = {ptr = 0x7fffbf7fdb60, fd = -1082139808, u32 = 3212827488, u64 = 140736406215520}}, {events = 0, data = {ptr = 0x4d95c, fd = 317788, u32 = 317788, u64 = 317788}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 3212827456, data = {ptr = 0x100007fff, fd = 32767, u32 = 32767, u64 = 4295000063}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 3019935236, data = {ptr = 0x2400007fff, fd = 32767, u32 = 32767, u64 = 154618855423}}, {events = 0, data = {ptr = 0x7fffb40084a8, fd = -1275034456, u32 = 3019932840, u64 = 140736213320872}}, {events = 16, data = {ptr = 0x1400000000, fd = 0, u32 = 0, u64 = 85899345920}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 132, data = {ptr = 0x2000007fff, fd = 32767, u32 = 32767, u64 = 137438986239}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7ffff7c4fb9f <pthread_setname_np+255>, fd = -138085473, u32 = 4156881823, u64 = 140737350269855}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 4153707608, data = {ptr = 0xb00007fff, fd = 32767, u32 = 32767, u64 = 47244673023}}, {events = 0, data = {ptr = 0x3115c1babac45700, fd = -1161537792, u32 = 3133429504, u64 = 3536946090110899968}}, {events = 1438970808, data = {ptr = 0xbf7fdc2000005555, fd = 21845, u32 = 21845, u64 = 13798989813283575125}}, {events = 32767, data = {ptr = 0x7fffbf7fdc50, fd = -1082139568, u32 = 3212827728, u64 = 140736406215760}}, {events = 3133429504, data = {ptr = 0xffffdaef3115c1ba, fd = 823509434, u32 = 823509434, u64 = 18446703319588389306}}, {events = 32767, data = {ptr = 0x555555c4c798, fd = 1438959512, u32 = 1438959512, u64 = 93824999540632}}}
        source = <optimized out>
        i = 0
        count = <optimized out>
        has_timers = <optimized out>
#18 0x00007ffff6293bc7 in wl_display_run (display=0x555555c4c770) at src/wayland-server.c:1351
#19 0x00007ffff7183fe7 in operator()(wl_display*) const (__closure=0x555555c4f3b8, d=0x555555c4c770) at /home/wmww/code/mir/src/server/frontend_wayland/wayland_connector.cpp:762
#20 0x00007ffff718741e in std::__invoke_impl<void, mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*>(std::__invoke_other, struct {...} &&) (__f=...)
    at /usr/include/c++/10.1.0/bits/invoke.h:60
#21 0x00007ffff718739b in std::__invoke<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*>(struct {...} &&) (__fn=...) at /usr/include/c++/10.1.0/bits/invoke.h:95
#22 0x00007ffff718730b in std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> >::_M_invoke<0, 1>(std::_Index_tuple<0, 1>) (this=0x555555c4f3b8)
    at /usr/include/c++/10.1.0/thread:264
#23 0x00007ffff7187290 in std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> >::operator()(void) (this=0x555555c4f3b8)
    at /usr/include/c++/10.1.0/thread:271
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x00007ffff7187234 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> > >::_M_run(void) (this=0x555555c4f3b0)
    at /usr/include/c++/10.1.0/thread:215
#25 0x00007ffff78d7b74 in std::execute_native_thread_routine(void*) (__p=0x555555c4f3b0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#26 0x00007ffff7c43422 in start_thread () at /usr/lib/libpthread.so.0
#27 0x00007ffff7724b83 in clone () at /usr/lib/libc.so.6
```

**Comment by wmww** [comment]
I can't reproduce, and I don't see any obvious potential problems. We've started using a standardized destroy listener system here, so the problem could very well have gone away. Closing until someone figures out how to repro.
