### ISSUE TITLE
mir_demo_server SIGSEGV in mir::wayland::Global::~Global()

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#1736]
Not a whole lot of detail, but:

```gdb
Thread 1 (Thread 0x7fa013846940 (LWP 151218)):
#0  0x00007fa01430af6d in wl_resource_post_event () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#1  0x00007fa01430ba62 in wl_global_remove () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#2  0x00007fa01430bac5 in wl_global_destroy () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#3  0x00007fa0146b4fcb in mir::wayland::Global::~Global() () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirwayland.so.1
#4  0x00007fa013670e41 in ?? () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-gbm-kms.so.18
#5  0x00007fa01366db0f in ?? () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-gbm-kms.so.18
#6  0x00007fa0150b1b98 in ?? () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#7  0x00007fa01505e6ee in ?? () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#8  0x00007fa0150b1b98 in ?? () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#9  0x00007fa014fc1246 in mir::shell::AbstractShell::~AbstractShell() () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#10 0x00007fa0150b1b98 in ?? () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#11 0x00007fa0150409bf in ?? () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#12 0x00007fa0150b1b98 in ?? () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#13 0x00007fa0150b1c8a in ?? () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#14 0x00007fa0150b41bf in mir::run_mir(mir::ServerConfiguration&, std::function<void (mir::DisplayServer&)>, std::function<void (int)> const&) () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#15 0x00007fa0150a47aa in mir::Server::run() () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmirserver.so.54
#16 0x00007fa0151d5b84 in miral::MirRunner::run_with(std::initializer_list<std::function<void (mir::Server&)> >) () from target:/snap/mir-test-tools/3893/usr/lib/x86_64-linux-gnu/libmiral.so.4
#17 0x00005633ad43eaee in main ()
```

**Comment by Saviq** [comment]
Full [gdb.txt](https://github.com/MirServer/mir/files/5277868/gdb.txt).

**Comment by wmww** [comment]
Due to #1689?
