### ISSUE TITLE
[Rawhide] starting an X11 client causes Mir server to crash

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1746]
With Mir master (build with #1745)

Start (say) miral-app and then launch xterm (Ctrl-Alt-X)...

Expect: xterm window appears
Actual: miral-shell crashes

**Comment by AlanGriffiths** [comment]
```plain
#0  0x00007f7c5a7809a5 in std::_Function_base::_Base_manager<mir::frontend::XWaylandSurface::XWaylandSurface(mir::frontend::XWaylandWM*, const std::shared_ptr<mir::frontend::XCBConnection>&, mir::frontend::WlSeat&, const std::shared_ptr<mir::shell::Shell>&, const std::shared_ptr<mir::frontend::XWaylandClientManager>&, xcb_window_t, const mir::geometry::Rectangle&, bool)::<lambda(auto:2)> >::_M_clone(std::_Any_data &, const std::_Any_data &, std::true_type) (__dest=..., __source=...) at /usr/include/c++/10/bits/std_function.h:152
#1  0x00007f7c5a77f8e1 in std::_Function_base::_Base_manager<mir::frontend::XWaylandSurface::XWaylandSurface(mir::frontend::XWaylandWM*, const std::shared_ptr<mir::frontend::XCBConnection>&, mir::frontend::WlSeat&, const std::shared_ptr<mir::shell::Shell>&, const std::shared_ptr<mir::frontend::XWaylandClientManager>&, xcb_window_t, const mir::geometry::Rectangle&, bool)::<lambda(auto:2)> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=std::__clone_functor) at /usr/include/c++/10/bits/std_function.h:196
#2  0x00007f7c5a77ead4 in std::_Function_handler<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&), mir::frontend::XWaylandSurface::XWaylandSurface(mir::frontend::XWaylandWM*, const std::shared_ptr<mir::frontend::XCBConnection>&, mir::frontend::WlSeat&, const std::shared_ptr<mir::shell::Shell>&, const std::shared_ptr<mir::frontend::XWaylandClientManager>&, xcb_window_t, const mir::geometry::Rectangle&, bool)::<lambda(auto:2)> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=std::__clone_functor)
    at /usr/include/c++/10/bits/std_function.h:283
#3  0x00007f7c5a766f75 in std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::function(std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&) (this=0x7f7bc67fe100, __x=...)
    at /usr/include/c++/10/bits/std_function.h:593
#4  0x00007f7c5a77dfa0 in (anonymous namespace)::property_handler<std::__cxx11::basic_string<char> >(const std::shared_ptr<mir::frontend::XCBConnection> &, xcb_window_t, xcb_atom_t, std::function<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>)
    (connection=std::shared_ptr<mir::frontend::XCBConnection> (use count 4, weak count 0) = {...}, window=4194334, property=67, handler=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_xwayland/xwayland_surface.cpp:140
#5  0x00007f7c5a77dfbd in (anonymous namespace)::property_handler<std::__cxx11::basic_string<char> >(const std::shared_ptr<mir::frontend::XCBConnection> &, xcb_window_t, xcb_atom_t, std::function<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>)
    (connection=std::shared_ptr<mir::frontend::XCBConnection> (use count 4, weak count 0) = {...}, window=4194334, property=67, handler=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_xwayland/xwayland_surface.cpp:140
#6  0x00007f7c5a77dfbd in (anonymous namespace)::property_handler<std::__cxx11::basic_string<char> >(const std::shared_ptr<mir::frontend::XCBConnection> &, xcb_window_t, xcb_atom_t, std::function<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>)
    (connection=std::shared_ptr<mir::frontend::XCBConnection> (use count 4, weak count 0) = {...}, window=4194334, property=67, handler=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_xwayland/xwayland_surface.cpp:140
#7  0x00007f7c5a77dfbd in (anonymous namespace)::property_handler<std::__cxx11::basic_string<char> >(const std::shared_ptr<mir::frontend::XCBConnection> &, xcb_window_t, xcb_atom_t, std::function<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>)
    (connection=std::shared_ptr<mir::frontend::XCBConnection> (use count 4, weak count 0) = {...}, window=4194334, property=67, handler=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_xwayland/xwayland_surface.cpp:140
#8  0x00007f7c5a77dfbd in (anonymous namespace)::property_handler<std::__cxx11::basic_string<char> >(const std::shared_ptr<mir::frontend::XCBConnection> &, xcb_window_t, xcb_atom_t, std::function<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>)
    (connection=std::shared_ptr<mir::frontend::XCBConnection> (use count 4, weak count 0) = {...}, window=4194334, property=67, handler=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_xwayland/xwayland_surface.cpp:140
#9  0x00007f7c5a77dfbd in (anonymous namespace)::property_handler<std::__cxx11::basic_string<char> >(const std::shared_ptr<mir::frontend::XCBConnection> &, xcb_window_t, xcb_atom_t, std::function<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>)
    (connection=std::shared_ptr<mir::frontend::XCBConnection> (use count 4, weak count 0) = {...}, window=4194334, property=67, handler=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_xwayland/xwayland_surface.cpp:140
#10 0x00007f7c5a77dfbd in (anonymous namespace)::property_handler<std::__cxx11::basic_string<char> >(const std::shared_ptr<mir::frontend::XCBConnection> &, xcb_window_t, xcb_atom_t, std::function<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>)
    (connection=std::shared_ptr<mir::frontend::XCBConnection> (use count 4, weak count 0) = {...}, window=4194334, property=67, handler=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_xwayland/xwayland_surface.cpp:140
#11 0x00007f7c5a77dfbd in (anonymous namespace)::property_handler<std::__cxx11::basic_string<char> >(const std::shared_ptr<mir::frontend::XCBConnection> &, xcb_window_t, xcb_atom_t, std::function<void(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>)
    (connection=std::shared_ptr<mir::frontend::XCBConnection> (use count 4, weak count 0) = {...}, window=4194334, property=67, handler=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_xwayland/xwayland_surface.cpp:140
```

(With lots more of the same frame)

**Comment by AlanGriffiths** [comment]
How does this ever work without recursing?

```c++
│   118         template<typename T>                                                                                                                    │
│   119         auto property_handler(                                                                                                                  │
│   120             std::shared_ptr<mf::XCBConnection> const& connection,                                                                               │
│   121             xcb_window_t window,                                                                                                                │
│   122             xcb_atom_t property,                                                                                                                │
│   123             mf::XCBConnection::Handler<T>&& handler) -> std::pair<xcb_atom_t, std::function<std::function<void()>()>>				│
│   124         {                                                                                                                                       │
│   125             return std::make_pair(                                                                                                              │
│   126                 property,                                                                                                                       │
│   127                 [connection, window, property, handler = std::move(handler)]()                                                                  │
│   128                 {                                                                                                                               │
│   129                     return connection->read_property(window, property, std::move(handler));                                                     │
│   130                 });                                                                                                                             │
│   131         }                                                                                                                                       │
│   132                                                                                                                                                 │
│   133         template<typename T>                                                                                                                    │
│   134         auto property_handler(                                                                                                                  │
│   135             std::shared_ptr<mf::XCBConnection> const& connection,                                                                               │
│   136             xcb_window_t window,                                                                                                                │
│   137             xcb_atom_t property,                                                                                                                │
│   138             std::function<void(T const&)> handler) -> std::pair<xcb_atom_t, std::function<std::function<void()>()>>				│
│   139         {                                                                                                                                       │
│  >140             return property_handler<T>(connection, window, property, {handler});                                                                │
│   141         }                                                                                                                                       │
│   142         }                                                                                                                                       │
```
