### ISSUE TITLE
[Mir-on-X] when using X-forwarding from a multipass VM egmde segfaults on exit

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1938]
I _suspect_ this is related to s/w rendering as I don't see it using X forwarding to real hardware.

To reproduce:
```plain
multipass launch -n demo-egmde-snap
multipass-enable-ssh demo-egmde-snap
multipass-egmde-install demo-egmde-snap
multipass-ssh-X demo-egmde-snap sh -lc egmde
```
Then `Ctrl-Alt-BkSp` to exit.

(Scripts from https://AlanGriffiths/multipass-utils)

**Comment by AlanGriffiths** [comment]
Here's a backtrace - seems the client is busy shutting down
```plain
#0  0x00007f10d9180fe1 in wl_map_insert_at (map=<optimized out>, flags=1, i=6, data=<optimized out>)
    at ../src/wayland-util.c:247
#1  0x00007f10d917ce85 in proxy_destroy (proxy=0x7f10ac006990) at ../src/wayland-client.c:503
#2  wl_proxy_destroy (proxy=0x7f10ac006990) at ../src/wayland-client.c:534
#3  0x0000558cb876a21f in wl_output_destroy (wl_output=0x7f10ac006990)
    at /usr/include/wayland-client-protocol.h:5401
#4  0x0000558cb876a4d7 in egmde::FullscreenClient::Output::~Output (this=0x7f10ac005b50, 
    __in_chrg=<optimized out>) at /home/ubuntu/egmde/egfullscreenclient.cpp:94
#5  0x0000558cb8770cb0 in std::default_delete<egmde::FullscreenClient::Output>::operator() (
    this=0x7f10ac01a010, __ptr=0x7f10ac005b50) at /usr/include/c++/9/bits/unique_ptr.h:81
#6  0x0000558cb876f996 in std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> >::~unique_ptr (this=0x7f10ac01a010, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/unique_ptr.h:292
#7  0x0000558cb8774668 in std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > >::~pair (this=0x7f10ac01a008, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_pair.h:208
#8  0x0000558cb877468c in __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > >, false> >::destroy<std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > > > (this=0x7f10ac004e20, __p=0x7f10ac01a008)
    at /usr/include/c++/9/ext/new_allocator.h:153
#9  0x0000558cb8773b7d in std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > >, false> > >::destroy<std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > > > (__a=..., __p=0x7f10ac01a008)
    at /usr/include/c++/9/bits/alloc_traits.h:497
#10 0x0000558cb877288b in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > >, false> > >::_M_deallocate_node (this=0x7f10ac004e20, __n=0x7f10ac01a000)
    at /usr/include/c++/9/bits/hashtable_policy.h:2102
#11 0x0000558cb877132c in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > >, false> > >::_M_deallocate_nodes (this=0x7f10ac004e20, __n=0x0)
    at /usr/include/c++/9/bits/hashtable_policy.h:2124
#12 0x0000558cb877005c in std::_Hashtable<unsigned int, std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > >, std::allocator<std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > > >, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::clear (this=0x7f10ac004e20)
    at /usr/include/c++/9/bits/hashtable.h:2028
#13 0x0000558cb876f8d4 in std::unordered_map<unsigned int, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> >, std::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<egmde::FullscreenClient::Output, std::default_delete<egmde::FullscreenClient::Output> > > > >::clear (this=0x7f10ac004e20)
    at /usr/include/c++/9/bits/unordered_map.h:843
#14 0x0000558cb876bae4 in egmde::FullscreenClient::~FullscreenClient (this=0x7f10ac004d10, 
    __in_chrg=<optimized out>) at /home/ubuntu/egmde/egfullscreenclient.cpp:327
#15 0x0000558cb875b464 in egmde::Launcher::Self::~Self (this=0x7f10ac004d10, __in_chrg=<optimized out>)
    at /home/ubuntu/egmde/eglauncher.cpp:491
#16 0x0000558cb875b6c9 in __gnu_cxx::new_allocator<egmde::Launcher::Self>::destroy<egmde::Launcher::Self> (this=0x7f10ac004d10, __p=0x7f10ac004d10) at /usr/include/c++/9/ext/new_allocator.h:153
```

**Comment by AlanGriffiths** [comment]
OK, this is an egmde bug, transferring
