### ISSUE TITLE
Intermittent deadlock when setting cursor

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2107]
On current master, setting the cursor seems to sometimes result in the Wayland thread locking up. Stack trace:
```
#0  futex_wait (private=0, expected=2, futex_word=0x7fffcc026548) at ../sysdeps/nptl/futex-internal.h:146
#1  __lll_lock_wait (futex=futex@entry=0x7fffcc026548, private=0) at lowlevellock.c:52
#2  0x00007ffff799c733 in __GI___pthread_mutex_lock (mutex=0x7fffcc026548) at ../nptl/pthread_mutex_lock.c:80
#3  0x00007ffff52b4902 in __gthread_mutex_lock(__gthread_mutex_t*) (__mutex=0x7fffcc026548) at /usr/include/x86_64-linux-gnu/c++/10/bits/gthr-default.h:749
#4  0x00007ffff52b4ab6 in std::mutex::lock() (this=0x7fffcc026548) at /usr/include/c++/10/bits/std_mutex.h:100
#5  0x00007ffff52baac3 in std::unique_lock<std::mutex>::lock() (this=0x7fffdf7fcf00) at /usr/include/c++/10/bits/unique_lock.h:138
#6  0x00007ffff52b924b in std::unique_lock<std::mutex>::unique_lock(std::mutex&) (this=0x7fffdf7fcf00, __m=...) at /usr/include/c++/10/bits/unique_lock.h:68
#7  0x00007ffff531abf2 in SharedWlBuffer::lock() const (this=0x7fffcc0332d0) at /home/wmww/code/mir/src/platforms/common/server/buffer_from_wl_shm.cpp:188
#8  0x00007ffff531b950 in WlShmBuffer::map_readable() (this=0x7fffcc033200) at /home/wmww/code/mir/src/platforms/common/server/buffer_from_wl_shm.cpp:390
#9  0x00007ffff76329d2 in (anonymous namespace)::BufferCursorImage::BufferCursorImage(std::shared_ptr<mir::graphics::Buffer>, mir::geometry::Displacement const&)
    (this=0x7fffcc0431c0, buffer=std::shared_ptr<class mir::graphics::Buffer> (use count 4, weak count 0) = {...}, hotspot=...) at /home/wmww/code/mir/src/server/frontend_wayland/wl_pointer.cpp:57
#10 0x00007ffff7637195 in __gnu_cxx::new_allocator<(anonymous namespace)::BufferCursorImage>::construct<(anonymous namespace)::BufferCursorImage, std::shared_ptr<mir::graphics::Buffer>, mir::geometry::Displacement&>((anonymous namespace)::BufferCursorImage*) (this=0x7fffdf7fd13f, __p=0x7fffcc0431c0) at /usr/include/c++/10/ext/new_allocator.h:150
#11 0x00007ffff7637036 in std::allocator_traits<std::allocator<(anonymous namespace)::BufferCursorImage> >::construct<(anonymous namespace)::BufferCursorImage, std::shared_ptr<mir::graphics::Buffer>, mir::geometry::Displacement&>(std::allocator_traits<std::allocator<(anonymous namespace)::BufferCursorImage> >::allocator_type&, (anonymous namespace)::BufferCursorImage*) (__a=..., __p=0x7fffcc0431c0)
    at /usr/include/c++/10/bits/alloc_traits.h:512
#12 0x00007ffff7636e1b in std::_Sp_counted_ptr_inplace<(anonymous namespace)::BufferCursorImage, std::allocator<(anonymous namespace)::BufferCursorImage>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::shared_ptr<mir::graphics::Buffer>, mir::geometry::Displacement&>(std::allocator<(anonymous namespace)::BufferCursorImage>) (this=0x7fffcc0431b0, __a=...) at /usr/include/c++/10/bits/shared_ptr_base.h:551
#13 0x00007ffff7636a13 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<(anonymous namespace)::BufferCursorImage, std::allocator<(anonymous namespace)::BufferCursorImage>, std::shared_ptr<mir::graphics::Buffer>, mir::geometry::Displacement&>((anonymous namespace)::BufferCursorImage*&, std::_Sp_alloc_shared_tag<std::allocator<(anonymous namespace)::BufferCursorImage> >)
    (this=0x7fffdf7fd2e8, __p=@0x7fffdf7fd2e0: 0x0, __a=...) at /usr/include/c++/10/bits/shared_ptr_base.h:682
#14 0x00007ffff7636786 in std::__shared_ptr<(anonymous namespace)::BufferCursorImage, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<(anonymous namespace)::BufferCursorImage>, std::shared_ptr<mir::graphics::Buffer>, mir::geometry::Displacement&>(std::_Sp_alloc_shared_tag<std::allocator<(anonymous namespace)::BufferCursorImage> >) (this=0x7fffdf7fd2e0, __tag=...)
    at /usr/include/c++/10/bits/shared_ptr_base.h:1371
#15 0x00007ffff763630b in std::shared_ptr<(anonymous namespace)::BufferCursorImage>::shared_ptr<std::allocator<(anonymous namespace)::BufferCursorImage>, std::shared_ptr<mir::graphics::Buffer>, mir::geometry::Displacement&>(std::_Sp_alloc_shared_tag<std::allocator<(anonymous namespace)::BufferCursorImage> >) (this=0x7fffdf7fd2e0, __tag=...) at /usr/include/c++/10/bits/shared_ptr.h:408
#16 0x00007ffff7635c1f in std::allocate_shared<(anonymous namespace)::BufferCursorImage, std::allocator<(anonymous namespace)::BufferCursorImage>, std::shared_ptr<mir::graphics::Buffer>, mir::geometry::Displacement&>(std::allocator<(anonymous namespace)::BufferCursorImage> const&) (__a=...) at /usr/include/c++/10/bits/shared_ptr.h:860
#17 0x00007ffff7635446 in std::make_shared<(anonymous namespace)::BufferCursorImage, std::shared_ptr<mir::graphics::Buffer>, mir::geometry::Displacement&>() () at /usr/include/c++/10/bits/shared_ptr.h:876
#18 0x00007ffff763496f in (anonymous namespace)::WlSurfaceCursor::apply_latest_buffer() (this=0x7fffcc050b90) at /home/wmww/code/mir/src/server/frontend_wayland/wl_pointer.cpp:512
#19 0x00007ffff76347d9 in (anonymous namespace)::WlSurfaceCursor::set_hotspot(mir::geometry::Displacement const&) (this=0x7fffcc050b90, new_hotspot=...)
    at /home/wmww/code/mir/src/server/frontend_wayland/wl_pointer.cpp:489
#20 0x00007ffff76342d1 in mir::frontend::WlPointer::on_commit(mir::frontend::WlSurface*) (this=0x7fffcc02a330, surface=0x7fffcc032580) at /home/wmww/code/mir/src/server/frontend_wayland/wl_pointer.cpp:435
#21 0x00007ffff7633e71 in (anonymous namespace)::CursorSurfaceRole::commit(mir::frontend::WlSurfaceState const&) (this=0x7fffcc050bc0, state=...)
    at /home/wmww/code/mir/src/server/frontend_wayland/wl_pointer.cpp:344
#22 0x00007ffff7614c40 in mir::frontend::WlSurface::commit() (this=0x7fffcc032580) at /home/wmww/code/mir/src/server/frontend_wayland/wl_surface.cpp:464
#23 0x00007ffff6a998a3 in mir::wayland::Surface::Thunks::commit_thunk(wl_client*, wl_resource*) (client=0x7fffcc02be40, resource=0x7fffcc02cc40)
    at /home/wmww/code/mir/src/wayland/generated/wayland_wrapper.cpp:1903
#24 0x00007ffff6c86249 in  () at /lib/x86_64-linux-gnu/libffi.so.8
#25 0x00007ffff6c85639 in  () at /lib/x86_64-linux-gnu/libffi.so.8
#26 0x00007ffff6855802 in wl_closure_invoke (closure=closure@entry=0x7fffcc00f0f0, flags=flags@entry=2, target=<optimized out>, target@entry=0x7fffcc02cc40, opcode=opcode@entry=6, data=<optimized out>, 
    data@entry=0x7fffcc02be40) at ../src/connection.c:1018
#27 0x00007ffff6850c82 in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x7fffcc02be40) at ../src/wayland-server.c:432
#28 0x00007ffff685372a in wl_event_loop_dispatch (loop=0x5555556f3560, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
#29 0x00007ffff68512c5 in wl_display_run (display=0x55555572b7d0) at ../src/wayland-server.c:1351
#30 0x00007ffff75d39a7 in operator()(wl_display*) const (__closure=0x555555b61ab8, d=0x55555572b7d0) at /home/wmww/code/mir/src/server/frontend_wayland/wayland_connector.cpp:643
#31 0x00007ffff75d63a0 in std::__invoke_impl<void, mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*>(std::__invoke_other, struct {...} &&) (__f=...)
    at /usr/include/c++/10/bits/invoke.h:60
#32 0x00007ffff75d631d in std::__invoke<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*>(struct {...} &&) (__fn=...) at /usr/include/c++/10/bits/invoke.h:95
#33 0x00007ffff75d628d in std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> >::_M_invoke<0, 1>(std::_Index_tuple<0, 1>) (this=0x555555b61ab8)
    at /usr/include/c++/10/thread:264
--Type <RET> for more, q to quit, c to continue without paging--
#34 0x00007ffff75d6246 in std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> >::operator()(void) (this=0x555555b61ab8)
    at /usr/include/c++/10/thread:271
#35 0x00007ffff75d622a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> > >::_M_run(void) (this=0x555555b61ab0)
    at /usr/include/c++/10/thread:215
#36 0x00007ffff7aa8694 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#37 0x00007ffff799a450 in start_thread (arg=0x7fffdf7fe640) at pthread_create.c:473
#38 0x00007ffff78bcd53 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by wmww** [comment]
It appears to be introduced in 536cd11510ba9e2c0dd6635ec5506eb65bc3ffb1
