### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#221]
I was testing a desktop session with several wayland cilents when it died with this error:

```
[2018-03-05 22:20:29.008065] <CRITICAL> input-event-access: capnproto/mir_event.capnp.h:4054: failed: expected (which() == Event::INPUT); Must check which() before get()ing a union member.
```

Unfortunately I have no idea what triggered it.

**Comment by AlanGriffiths** [comment]
Reproduce with a core...
```
#0  0x00007f0873589e97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f087358b801 in __GI_abort () at abort.c:79
#2  0x00007f0874bd6736 in mir_pointer_event_axis_value(MirPointerEvent const*, MirPointerAxis) (pev=0x7f085c0922c0, axis=mir_pointer_axis_y) at /home/alan/display_server/mir/src/client/input/input_event.cpp:272
#3  0x00007f0872eceeeb in (anonymous namespace)::send_motion_event_to_moved_surface(const (anonymous namespace)::SceneChangeContext &, const mir::scene::Surface *, const std::function<void(const std::shared_ptr<mir::input::Surface>&, const MirEvent*)> &) (ctx=..., moved_surface=0x7f0864481b40, send_motion=...)
    at /home/alan/display_server/mir/src/server/input/surface_input_dispatcher.cpp:402
#4  0x00007f0872ecf27a in mir::input::SurfaceInputDispatcher::surface_moved(mir::scene::Surface const*) (this=0x560c9d585dc0, moved_surface=0x7f0864481b40)
    at /home/alan/display_server/mir/src/server/input/surface_input_dispatcher.cpp:429
#5  0x00007f0872edc6db in std::__invoke_impl<void, void (mir::input::SurfaceInputDispatcher::* const&)(mir::scene::Surface const*), mir::input::SurfaceInputDispatcher*&, mir::scene::Surface const*>(std::__invoke_memfun_deref, void (mir::input::SurfaceInputDispatcher::* const&)(mir::scene::Surface const*), mir::input::SurfaceInputDispatcher*&, mir::scene::Surface const*&&) (__f=
    @0x560c9d576b70: (void (mir::input::SurfaceInputDispatcher::*)(mir::input::SurfaceInputDispatcher * const, const mir::scene::Surface *)) 0x7f0872ecf102 <mir::input::SurfaceInputDispatcher::surface_moved(mir::scene::Surface const*)>, __t=@0x560c9d576b80: 0x560c9d585dc0, __args#0=@0x7f08637fcdd0: 0x7f0864481b40)
    at /usr/include/c++/7/bits/invoke.h:73
#6  0x00007f0872edc5b9 in std::__invoke<void (mir::input::SurfaceInputDispatcher::* const&)(mir::scene::Surface const*), mir::input::SurfaceInputDispatcher*&, mir::scene::Surface const*>(void (mir::input::SurfaceInputDispatcher::* const&)(mir::scene::Surface const*), mir::input::SurfaceInputDispatcher*&, mir::scene::Surface const*&&) (__fn=
    @0x560c9d576b70: (void (mir::input::SurfaceInputDispatcher::*)(mir::input::SurfaceInputDispatcher * const, const mir::scene::Surface *)) 0x7f0872ecf102 <mir::input::SurfaceInputDispatcher::surface_moved(mir::scene::Surface const*)>, __args#0=@0x560c9d576b80: 0x560c9d585dc0, __args#1=@0x7f08637fcdd0: 0x7f0864481b40)
    at /usr/include/c++/7/bits/invoke.h:95
#7  0x00007f0872edc50b in std::_Mem_fn_base<void (mir::input::SurfaceInputDispatcher::*)(mir::scene::Surface const*), true>::operator()<mir::input::SurfaceInputDispatcher*&, mir::scene::Surface const*>(mir::input::SurfaceInputDispatcher*&, mir::scene::Surface const*&&) const (this=0x560c9d576b70, __args#0=@0x560c9d576b80: 0x560c9d585dc0, __args#1=@0x7f08637fcdd0: 0x7f0864481b40) at /usr/include/c++/7/functional:175
#8  0x00007f0872edc463 in std::__invoke_impl<void, std::_Mem_fn<void (mir::input::SurfaceInputDispatcher::*)(mir::scene::Surface const*)>&, mir::input::SurfaceInputDispatcher*&, mir::scene::Surface const*>(std::__invoke_other, std::_Mem_fn<void (mir::input::SurfaceInputDispatcher::*)(mir::scene::Surface const*)>&, mir::input::SurfaceInputDispatcher*&, mir::scene::Surface const*&&) (__f=..., __args#0=@0x560c9d576b80: 0x560c9d585dc0, __args#1=@0x7f08637fcdd0: 0x7f0864481b40) at /usr/include/c++/7/bits/invoke.h:60
```
