### ISSUE TITLE
Failing to run nested on GNOME/Wayland

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2434]
I've been trying to test #2432, but failed to run any bit of Mir on 22.04 on GNOME in a Wayland session.

With stable, it segfaults in `wl_proxy_get_version`:
```gdb
$ env -u DISPLAY -u WAYLAND_DISPLAY MIR_SERVER_WAYLAND_HOST=${WAYLAND_DISPLAY} gdb -args mir_demo_server
# ...
#0  0x00007ffff72ade94 in wl_proxy_get_version () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#1  0x00007ffff574861a in wl_shell_get_shell_surface (surface=0x5555555ff010, wl_shell=0x0) at /usr/include/wayland-client-protocol.h:3024
        id = <optimized out>

            shell_surface_listener = {ping = 0x7ffff57483c0 <_FUN(void*, wl_shell_surface*, uint32_t)>, configure = 0x7ffff5748260 <_FUN(void*, wl_shell_surface*, uint32_t, int32_t, int32_t)>, popup_done = 0x7ffff5748270 <_FUN(void*, wl_shell_surface*)>}
        size = <optimized out>
#2  mir::graphics::wayland::DisplayClient::Output::for_each_display_buffer(std::function<void (mir::graphics::DisplayBuffer&)> const&) (this=0x555555636690, f=...)
    at ./src/platforms/wayland/displayclient.cpp:305

            shell_surface_listener = {ping = 0x7ffff57483c0 <_FUN(void*, wl_shell_surface*, uint32_t)>, configure = 0x7ffff5748260 <_FUN(void*, wl_shell_surface*, uint32_t, int32_t, int32_t)>, popup_done = 0x7ffff5748270 <_FUN(void*, wl_shell_surface*)>}
        size = <optimized out>
# ...
```
[gdb_stable.txt](https://github.com/MirServer/mir/files/8764407/gdb_stable.txt)
[mir_stable.txt](https://github.com/MirServer/mir/files/8764552/mir_stable.txt)

With the RC, it fails to compile a shared and then segfaults as above:
```plain
[2022-05-24 18:18:55.197567] < - ERROR - > : failed to create BasicScreenShooter: ./src/renderers/gl/renderer.cpp(232): Throw in function static GLuint mir::renderer::gl::Renderer::ProgramFactory::compile_shader(GLenum, const GLchar*)
Dynamic exception type: boost::wrapexcept<std::system_error>
std::exception::what: Failed to create shader: GL_INVALID_OPERATION (0x502)

[2022-05-24 18:18:55.198687] <information> gbm-kms-buffer-allocator: Enabled linux-dmabuf import support
unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running
```
[gdb_rc.txt](https://github.com/MirServer/mir/files/8764549/gdb_rc.txt)
[mir_rc.txt](https://github.com/MirServer/mir/files/8764546/mir_rc.txt)

**Comment by wmww** [comment]
Fixes by #2437
