### ISSUE TITLE
Core dump after using OSK with Chromium

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2454]
This happened on 20.04, but as everything is snapped I don't think this is the issue.

The snaps:

* `chromium` 102.0.5005.61 (stable)
* `egmde` 155-mir2.8.0+dev185-snap197 (edge)
* `ubuntu-frame-osk` 38-squeekboard-v1.17.1 (candidate)

I have `ubuntu-frame-osk` listed in the configuration:
```
$ grep osk ~/.config/egmde.config 
shell-components=/snap/egmde/current/bin/swaybg.launcher:/snap/egmde/current/bin/waybar.launcher:ubuntu-frame-osk
```

First, start egmde (`egmde`) and launch a terminal (`Ctrl-Alt-Shift-T`). Then in the nested terminal enter:
```
chromium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland --enable-wayland-ime
```
This should bring up chromium as a Wayland client (if not, make sure the wayland plug is connected).

Put the focus on the address field (which brings up the terminal)

Now close the app by clicking on the close button

Expect: egmde continues to work
Actual: egmde crashes after a few seconds with:
```
Debug: Tried to remove global 5 but it is not registered as an output: NotFound
Mir fatal error: Unsupported attempt to continue after a fatal signal: SIGSEGV
Mir fatal error: Unsupported attempt to continue after a fatal signal: SIGABRT
Gdk-Message: 17:05:42.303: Error reading events from display: Broken pipe
Gdk-Message: 17:05:42.303: Error reading events from display: Broken pipe
Gdk-Message: 17:05:42.303: Error reading events from display: Broken pipe
Aborted (core dumped)
```

I also reproduced with the latest mir-demos from ppa:mir-team/dev
```
miral-app -demo-server
...
```

**Comment by AlanGriffiths** [comment]
A bit more information: the crash happens when the mouse pointer moves:
```
0x00007ffff71b1593 in std::__detail::_Mod_range_hashing::operator() (
    this=0x7ffff4e13660 <vtable for mir::renderer::software::WriteMappableBuffer+16>, 
    __num=140736481726128, __den=0) at /usr/include/c++/9/bits/hashtable_policy.h:433
433	    { return __num % __den; }
(gdb) bt
#0  0x00007ffff71b1593 in std::__detail::_Mod_range_hashing::operator()(unsigned long, unsigned long) const
    (this=0x7ffff4e13660 <vtable for mir::renderer::software::WriteMappableBuffer+16>, __num=140736481726128, __den=0) at /usr/include/c++/9/bits/hashtable_policy.h:433
#1  0x00007ffff73c5800 in std::__detail::_Hash_code_base<wl_client*, std::pair<wl_client* const, std::vector<mir::frontend::WlPointer*, std::allocator<mir::frontend::WlPointer*> > >, std::__detail::_Select1st, std::hash<wl_client*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, false>::_M_bucket_index(wl_client* const&, unsigned long, unsigned long) const
    (this=0x7ffff4e13660 <vtable for mir::renderer::software::WriteMappableBuffer+16>, __c=140736481726128, __n=0) at /usr/include/c++/9/bits/hashtable_policy.h:1297
#2  0x00007ffff73c2a52 in std::_Hashtable<wl_client*, std::pair<wl_client* const, std::vector<mir::frontend::WlPointer*, std::allocator<mir::frontend::WlPointer*> > >, std::allocator<std::pair<wl_client* const, std::vector<mir::frontend::WlPointer*, std::allocator<mir::frontend::WlPointer*> > > >, std::__detail::_Select1st, std::equal_to<wl_client*>, std::hash<wl_client*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_bucket_index(wl_client* const&, unsigned long) const
    (this=0x7ffff4e13660 <vtable for mir::renderer::software::WriteMappableBuffer+16>, __k=@0x7fffd9ffa650: 0x7fffc4000eb0, __c=140736481726128) at /usr/include/c++/9/bits/hashtable.h:676
#3  0x00007ffff73c0bfb in std::__detail::_Map_base<wl_client*, std::pair<wl_client* const, std::vector<mir::frontend::WlPointer*, std::allocator<mir::frontend::WlPointer*> > >, std::allocator<std::pair<wl_client* const, std::vector<mir::frontend::WlPointer*, std::allocator<mir::frontend::WlPointer*> > > >, std::__detail::_Select1st, std::equal_to<wl_client*>, std::hash<wl_client*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::operator[](wl_client* const&)
    (this=0x7ffff4e13660 <vtable for mir::renderer::software::WriteMappableBuffer+16>, __k=@0x7fffd9ffa650: 0x7fffc4000eb0) at /usr/include/c++/9/bits/hashtable_policy.h:696
#4  0x00007ffff73bf82d in std::unordered_map<wl_client*, std::vector<mir::frontend::WlPointer*, std::allocator<mir::frontend::WlPointer*> >, std::hash<wl_client*>, std::equal_to<wl_client*>, std::allocator<std::pair<wl_client* const, std::vector<mir::frontend::WlPointer*, std::allocator<mir::frontend::WlPointer*> > > > >::operator[](wl_client* const&)
    (this=0x7ffff4e13660 <vtable for mir::renderer::software::WriteMappableBuffer+16>, __k=@0x7fffd9ffa650: 0x7fffc4000eb0) at /usr/include/c++/9/bits/unordered_map.h:986
#5  0x00007ffff73be65a in mir::frontend::WlSeat::ListenerList<mir::frontend::WlPointer>::for_each(wl_client*, std::function<void (mir::frontend::WlPointer*)>)
    (this=0x7ffff4e13660 <vtable for mir::renderer::software::WriteMappableBuffer+16>, client=0x7fffc4000eb0, func=...) at /home/alan/CLionProjects/mir/src/server/frontend_wayland/wl_seat.cpp:76
#6  0x00007ffff73ba937 in mir::frontend::WlSeat::for_each_listener(wl_client*, std::function<void (mir::frontend::WlPointer*)>) (this=0x55555612bb70, client=0x7fffc4000eb0, func=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_wayland/wl_seat.cpp:237
#7  0x00007ffff7387859 in mir::frontend::WaylandInputDispatcher::handle_event(MirInputEvent const*)
    (this=0x7fffc400be20, event=0x7fffc0019560)
    at /home/alan/CLionProjects/mir/src/server/frontend_wayland/wayland_input_dispatcher.cpp:60
#8  0x00007ffff7383757 in mir::frontend::WaylandSurfaceObserver::<lambda(mir::frontend::WaylandSurfaceObserver::Impl*, mir::frontend::WindowWlSurfaceRole*)>::operator()(mir::frontend::WaylandSurfaceObserver::Impl *, mir::frontend::WindowWlSurfaceRole *) const (__closure=0x7fffc4050130, impl=0x7fffc400c760)
    at /home/alan/CLionProjects/mir/src/server/frontend_wayland/wayland_surface_observer.cpp:116
#9  0x00007ffff7384782 in std::_Function_handler<void(mir::frontend::WaylandSurfaceObserver::Impl*, mir::frontend::WindowWlSurfaceRole*), mir::frontend::WaylandSurfaceObserver::input_consumed(const mir::scene::Surface*, const MirEvent*)::<lambda(mir::frontend::WaylandSurfaceObserver::Impl*, mir::frontend::WindowWlSurfaceRole*)> >::_M_invoke(const std::_Any_data &, mir::frontend::WaylandSurfaceObserver::Impl *&&, mir::frontend::WindowWlSurfaceRole *&&) (__functor=..., __args#0=@0x7fffd9ffa830: 0x7fffc400c760, __args#1=
    @0x7fffd9ffa828: 0x7fffc400c5d8) at /usr/include/c++/9/bits/std_function.h:300
#10 0x00007ffff7385e21 in std::function<void (mir::frontend::WaylandSurfaceObserver::Impl*, mir::frontend::WindowWlSurfaceRole*)>::operator()(mir::frontend::WaylandSurfaceObserver::Impl*, mir::frontend::WindowWlSurfaceRole*) const (this=0x7fffc409b320, __args#0=0x7fffc400c760, __args#1=0x7fffc400c5d8)
    at /usr/include/c++/9/bits/std_function.h:688
#11 0x00007ffff738397b in mir::frontend::WaylandSurfaceObserver::<lambda()>::operator()(void) const
    (__closure=0x7fffc409b310)
    at /home/alan/CLionProjects/mir/src/server/frontend_wayland/wayland_surface_observer.cpp:134
#12 0x00007ffff73848e4 in std::_Function_handler<void(), mir::frontend::WaylandSurfaceObserver::run_on_wayland_thread_unless_window_destroyed(std::function<void(mir::frontend::WaylandSurfaceObserver::Impl*, mir::frontend::WindowWlSurfaceRole*)>&&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/9/bits/std_function.h:300
#13 0x00007ffff718ac4a in std::function<void ()>::operator()() const (this=0x7fffd9ffa910)
    at /usr/include/c++/9/bits/std_function.h:688
#14 0x00007ffff7380a6f in mir::frontend::WaylandExecutor::State::on_notify(int, unsigned int, void*)
    (fd=16, data=0x555556134bc0)
    at /home/alan/CLionProjects/mir/src/server/frontend_wayland/wayland_executor.cpp:238
#15 0x00007ffff675f65a in wl_event_loop_dispatch () at /lib/x86_64-linux-gnu/libwayland-server.so.0
#16 0x00007ffff675dbd5 in wl_display_run () at /lib/x86_64-linux-gnu/libwayland-server.so.0
#17 0x00007ffff737175d in mir::frontend::WaylandConnector::<lambda(wl_display*)>::operator()(wl_display *) const (__closure=0x5555561327f8, d=0x555556138740)
    at /home/alan/CLionProjects/mir/src/server/frontend_wayland/wayland_connector.cpp:391
#18 0x00007ffff73739e2 in std::__invoke_impl<void, mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*>(std::__invoke_other, mir::frontend::WaylandConnector::<lambda(wl_display*)> &&)
    (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#19 0x00007ffff737395e in std::__invoke<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*>(mir::frontend::WaylandConnector::<lambda(wl_display*)> &&) (__fn=...)
    at /usr/include/c++/9/bits/invoke.h:95
#20 0x00007ffff73738cd in std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> >::_M_invoke<0, 1>(std::_Index_tuple<0, 1>) (this=0x5555561327f8)
    at /usr/include/c++/9/thread:244
--Type <RET> for more, q to quit, c to continue without paging--q
Quit
(gdb) f 6
#6  0x00007ffff73ba937 in mir::frontend::WlSeat::for_each_listener(wl_client*, std::function<void (mir::frontend::WlPointer*)>) (this=0x55555612bb70, client=0x7fffc4000eb0, func=...)
    at /home/alan/CLionProjects/mir/src/server/frontend_wayland/wl_seat.cpp:237
237	    pointer_listeners->for_each(client, func);
```
