### ISSUE TITLE
Snapped, nested on Nvidia/eglstream doesn't work

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2462]
```plain
$ sudo snap run --shell mir-test-tools.smoke-test
$ cd $SNAP
$ ./usr/bin/mir_demo_server
# happy
```

But then, in a different terminal:
```plain
$ sudo snap run --shell mir-test-tools.smoke-test
$ cd $SNAP
$ ./usr/bin/mir_demo_client_wayland_egl_spinner
# happy

$ env WAYLAND_DISPLAY=wayland-1 MIR_SERVER_WAYLAND_HOST=wayland-0 ./usr/bin/mir_demo_server
# unhappy
[2022-06-08 16:49:18.076592] <information> GLRenderer: GL framebuffer bits: RGBA=5650, depth=0, stencil=0
mir_demo_server: ../src/wayland-thread.c:92: wlExternalApiLock: Assertion `!"failed to lock pthread mutex"' failed.
```

As @RAOF noted, at least the selected pixel format is weird.

**Comment by RAOF** [comment]
Oooof.

Ok, this
```
../src/wayland-thread.c:92: wlExternalApiLock: Assertion `!"failed to lock pthread mutex"' failed.
```
looks like it's coming from the nvidia external EGL platform; I can't find it now, but we've hit `glvnd` locking bugs in the past with having both a server and a client in the same process. This might be a similar bug?

The Ubuntu Frame version is even more weirdness; it looks like file descriptors aren't being sent? Actually, maybe this is a *confinement* issue? We've had AppArmor fiddling with the file descriptors we've sent over the wire in the past.

**Comment by AlanGriffiths** [comment]
> $ sudo mir-test-tools.performance-test --gtest_filter=Hosted*

Curiosity again: does the same happen in a logind session without sudo?

**Comment by Saviq** [comment]
> Curiosity again: does the same happen in a logind session without sudo?

It does, yes.

> The Ubuntu Frame version is even more weirdness; it looks like file descriptors aren't being sent? Actually, maybe this is a _confinement_ issue? We've had AppArmor fiddling with the file descriptors we've sent over the wire in the past.

FWIW I just confirmed this happens outside of snaps as well.

```shell
$ WAYLAND_DISPLAY=wayland-99 mir_demo_server --wayland-host wayland-0
# ...

mir_demo_server: ../src/wayland-thread.c:87: wlExternalApiLock: Assertion `!"failed to lock pthread mutex"' failed.
!!! Fatal signal received. Attempting cleanup, but deadlock may occur
Mir fatal error: Unsupported attempt to continue after a fatal signal: SIGABRT
Aborted
```

<details>
<summary>gdb.txt</summary>

```gdb
  Id   Target Id                                          Frame 
  1    Thread 0x7ffff689a700 (LWP 8271) "mir_demo_server" 0x00007ffff7888d7f in __GI___poll (fds=0x555555746d60, nfds=2, timeout=967) at ../sysdeps/unix/sysv/linux/poll.c:29
  2    Thread 0x7ffff688f640 (LWP 8275) "mir_demo_se-ust" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  3    Thread 0x7ffff608e640 (LWP 8276) "mir_demo_se-ust" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  4    Thread 0x7ffff5673640 (LWP 8277) "gmain"           0x00007ffff7888d7f in __GI___poll (fds=0x5555556173c0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  5    Thread 0x7ffff4e72640 (LWP 8278) "gdbus"           0x00007ffff7888d7f in __GI___poll (fds=0x5555556296e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  7    Thread 0x7fffed204640 (LWP 8281) "EglStrmComm*AF1" __libc_recv (flags=<optimized out>, len=56, buf=0x7fffed1fbba0, fd=22) at ../sysdeps/unix/sysv/linux/recv.c:28
  8    Thread 0x7fffeca03640 (LWP 8283) "mir_demo_server" 0x00007ffff7888d7f in __GI___poll (fds=0x7fffec9faca0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  9    Thread 0x7fffe7e6e640 (LWP 8284) "mir_demo_server" __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555555682d30) at ./nptl/futex-internal.c:57
  10   Thread 0x7fffdda57640 (LWP 8285) "Mir/Comp"        __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555577478c) at ./nptl/futex-internal.c:57
  11   Thread 0x7fffdd256640 (LWP 8286) "Mir/Input Reade" 0x00007ffff7888d7f in __GI___poll (fds=fds@entry=0x7fffdd24dd98, nfds=nfds@entry=1, timeout=timeout@entry=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
  12   Thread 0x7fffdca55640 (LWP 8287) "CPMMListener"    0x00007ffff7888d7f in __GI___poll (fds=0x7fffdca4ce38, nfds=1, timeout=300000) at ../sysdeps/unix/sysv/linux/poll.c:29
* 13   Thread 0x7fffcffff640 (LWP 8288) "Mir/Wayland"     __pthread_kill_implementation (no_tid=0, signo=6, threadid=140736683046464) at ./nptl/pthread_kill.c:44
  14   Thread 0x7fffcf680640 (LWP 8292) "Mir/Workqueue"   syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38

Thread 14 (Thread 0x7fffcf680640 (LWP 8292) "Mir/Workqueue"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff7c7fc39 in std::__detail::__platform_wait<int> (__val=0, __addr=<optimized out>) at /usr/include/c++/11/bits/atomic_wait.h:106
#2  std::__atomic_wait_address_bare<std::__atomic_semaphore::_M_acquire()::{lambda()#1}>(int const*, std::__atomic_semaphore::_M_acquire()::{lambda()#1}) (__pred=..., __addr=<optimized out>) at /usr/include/c++/11/bits/atomic_wait.h:451
#3  std::__atomic_semaphore::_M_acquire (this=<optimized out>) at /usr/include/c++/11/bits/semaphore_base.h:218
#4  std::counting_semaphore<1l>::acquire (this=<optimized out>) at /usr/include/c++/11/semaphore:72
#5  (anonymous namespace)::Worker::work_loop (me=0x7fffb8042a20, shutdown_channel=...) at ./src/common/thread_pool_executor.cpp:181
#6  0x00007ffff7a942b3 in std::execute_native_thread_routine (__p=0x7fffb80275b0) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:82
#7  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 13 (Thread 0x7fffcffff640 (LWP 8288) "Mir/Wayland"):
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140736683046464) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140736683046464) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140736683046464, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff77b2476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff77987f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff779871b in __assert_fail_base (fmt=0x7ffff794d150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff5711b80 "!\"failed to lock pthread mutex\"", file=0x7ffff5711000 "../src/wayland-thread.c", line=87, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff77a9e96 in __GI___assert_fail (assertion=assertion@entry=0x7ffff5711b80 "!\"failed to lock pthread mutex\"", file=file@entry=0x7ffff5711000 "../src/wayland-thread.c", line=line@entry=87, function=function@entry=0x7ffff5711d00 <__PRETTY_FUNCTION__.2.lto_priv.0> "wlExternalApiLock") at ./assert/assert.c:101
#7  0x00007ffff570d279 in wlExternalApiLock () at ../src/wayland-thread.c:87
#8  0x00007ffff570dc3a in wlEglAcquireDisplay (dpy=dpy@entry=0x555555598440) at ../src/wayland-egldisplay.c:684
#9  0x00007ffff570eab8 in wlEglGetInternalHandleExport (dpy=<optimized out>, type=<optimized out>, handle=0x555555598440) at ../src/wayland-eglhandle.c:167
#10 0x00007ffff42a7be5 in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#11 0x00007ffff424b65d in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#12 0x00007ffff570f167 in wlEglCreateStreamAttribHook (dpy=0x555555598440, attribs=0x7fffcfff66a0) at ../src/wayland-eglstream.c:200
#13 0x00007ffff42ad03a in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#14 0x00007ffff424b6b0 in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#15 0x00007ffff586d5a3 in ?? () from /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-eglstream-kms.so.20
#16 0x00007ffff6ec3e2e in ffi_call_unix64 () at ../src/x86/unix64.S:105
#17 0x00007ffff6ec0493 in ffi_call_int (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>) at ../src/x86/ffi64.c:672
#18 0x00007ffff71c7260 in wl_closure_invoke (closure=closure@entry=0x7fffb8005ff0, target=<optimized out>, target@entry=0x7fffb804bd50, opcode=opcode@entry=0, data=<optimized out>, data@entry=0x7fffb8000ee0, flags=<optimized out>) at ../src/connection.c:1025
#19 0x00007ffff71cb474 in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x7fffb8000ee0) at ../src/wayland-server.c:437
#20 0x00007ffff71c9eea in wl_event_loop_dispatch (loop=0x555555687220, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
#21 0x00007ffff71ca6c5 in wl_display_run (display=0x7fffd00133a0) at ../src/wayland-server.c:1408
#22 0x00007ffff7a942b3 in std::execute_native_thread_routine (__p=0x555555746d40) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:82
#23 0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#24 0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 12 (Thread 0x7fffdca55640 (LWP 8287) "CPMMListener"):
#0  0x00007ffff7888d7f in __GI___poll (fds=0x7fffdca4ce38, nfds=1, timeout=300000) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fffee5f1417 in ?? () from /lib/x86_64-linux-gnu/libnvidia-eglcore.so.515.86.01
#2  0x00007fffee5efd7a in ?? () from /lib/x86_64-linux-gnu/libnvidia-eglcore.so.515.86.01
#3  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#4  0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 11 (Thread 0x7fffdd256640 (LWP 8286) "Mir/Input Reade"):
#0  0x00007ffff7888d7f in __GI___poll (fds=fds@entry=0x7fffdd24dd98, nfds=nfds@entry=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff7c776c3 in poll (__timeout=-1, __nfds=1, __fds=0x7fffdd24dd98) at /usr/include/x86_64-linux-gnu/bits/poll2.h:39
#2  (anonymous namespace)::dispatch_loop(const std::string &, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::Dispatchable>, const std::function<void()> &) (name=..., thread_register=..., dispatcher=..., exception_handler=...) at ./src/common/dispatch/threaded_dispatcher.cpp:199
#3  0x00007ffff7c70411 in std::__invoke_impl<void, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::Dispatchable>, std::function<void ()> const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::MultiplexingDispatchable>, std::function<void ()> >(std::__invoke_other, void (*&&)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::Dispatchable>, std::function<void ()> const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>&&, std::shared_ptr<mir::dispatch::MultiplexingDispatchable>&&, std::function<void ()>&&) (__f=<optimized out>, __f=<optimized out>) at /usr/include/c++/11/bits/invoke.h:61
#4  std::__invoke<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::Dispatchable>, std::function<void ()> const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::MultiplexingDispatchable>, std::function<void ()> >(void (*&&)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::Dispatchable>, std::function<void ()> const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>&&, std::shared_ptr<mir::dispatch::MultiplexingDispatchable>&&, std::function<void ()>&&) (__fn=<optimized out>) at /usr/include/c++/11/bits/invoke.h:96
#5  std::thread::_Invoker<std::tuple<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::Dispatchable>, std::function<void ()> const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::MultiplexingDispatchable>, std::function<void ()> > >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) (this=<optimized out>) at /usr/include/c++/11/bits/std_thread.h:253
#6  std::thread::_Invoker<std::tuple<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::Dispatchable>, std::function<void ()> const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::MultiplexingDispatchable>, std::function<void ()> > >::operator()() (this=<optimized out>) at /usr/include/c++/11/bits/std_thread.h:260
#7  std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::Dispatchable>, std::function<void ()> const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<mir::dispatch::ThreadedDispatcher::ThreadShutdownRequestHandler>, std::shared_ptr<mir::dispatch::MultiplexingDispatchable>, std::function<void ()> > > >::_M_run() (this=<optimized out>) at /usr/include/c++/11/bits/std_thread.h:211
#8  0x00007ffff7a942b3 in std::execute_native_thread_routine (__p=0x5555557a9c20) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:82
#9  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#10 0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 10 (Thread 0x7fffdda57640 (LWP 8285) "Mir/Comp"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555577478c) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x55555577478c) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555577478c, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff7803ac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555555774738, cond=0x555555774760) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555555774760, mutex=0x555555774738) at ./nptl/pthread_cond_wait.c:627
#5  0x00007ffff7d97c0d in std::condition_variable::wait<mir::compositor::CompositingFunctor::operator()()::{lambda()#8}>(std::unique_lock<std::mutex>&, mir::compositor::CompositingFunctor::operator()()::{lambda()#8}) (__p=..., __lock=..., this=0x555555774760) at /usr/include/c++/11/condition_variable:103
#6  mir::compositor::CompositingFunctor::operator() (this=0x555555774700) at compositor/./src/server/compositor/multi_threaded_compositor.cpp:125
#7  0x00007ffff7c7b163 in std::function<void ()>::operator()() const (this=0x5555556103f0) at /usr/include/c++/11/bits/std_function.h:590
#8  operator() (__closure=0x5555556103d0) at ./src/common/thread_pool_executor.cpp:266
#9  std::__invoke_impl<void, (anonymous namespace)::ThreadPool::spawn(std::function<void()>&&)::<lambda()>&> (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#10 std::__invoke_r<void, (anonymous namespace)::ThreadPool::spawn(std::function<void()>&&)::<lambda()>&> (__fn=...) at /usr/include/c++/11/bits/invoke.h:111
#11 std::_Function_handler<void(), (anonymous namespace)::ThreadPool::spawn(std::function<void()>&&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/11/bits/std_function.h:290
#12 0x00007ffff7c7fba7 in std::function<void ()>::operator()() const (this=0x7fffdda4ee10) at /usr/include/c++/11/bits/std_function.h:590
#13 (anonymous namespace)::Worker::work_loop (me=0x5555556108b0, shutdown_channel=...) at ./src/common/thread_pool_executor.cpp:184
#14 0x00007ffff7a942b3 in std::execute_native_thread_routine (__p=0x55555575c4f0) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:82
#15 0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#16 0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 9 (Thread 0x7fffe7e6e640 (LWP 8284) "mir_demo_server"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555555682d30) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x555555682d30) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555555682d30, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff7803ac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555555682ce0, cond=0x555555682d08) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555555682d08, mutex=0x555555682ce0) at ./nptl/pthread_cond_wait.c:627
#5  0x00007ffff77473d1 in ?? () from /lib/x86_64-linux-gnu/libmirplatform.so.25
#6  0x00007ffff7a942b3 in std::execute_native_thread_routine (__p=0x555555743bc0) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:82
#7  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 8 (Thread 0x7fffeca03640 (LWP 8283) "mir_demo_server"):
#0  0x00007ffff7888d7f in __GI___poll (fds=0x7fffec9faca0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff56eeae9 in ?? () from /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-wayland.so.20
#2  0x00007ffff7a942b3 in std::execute_native_thread_routine (__p=0x555555763f20) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:82
#3  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#4  0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 7 (Thread 0x7fffed204640 (LWP 8281) "EglStrmComm*AF1"):
#0  __libc_recv (flags=<optimized out>, len=56, buf=0x7fffed1fbba0, fd=22) at ../sysdeps/unix/sysv/linux/recv.c:28
#1  __libc_recv (fd=22, buf=0x7fffed1fbba0, len=56, flags=0) at ../sysdeps/unix/sysv/linux/recv.c:23
#2  0x00007ffff4279603 in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#3  0x00007ffff427a3cd in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#4  0x00007ffff426f52d in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#5  0x00007ffff42beade in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#6  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#7  0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 5 (Thread 0x7ffff4e72640 (LWP 8278) "gdbus"):
#0  0x00007ffff7888d7f in __GI___poll (fds=0x5555556296e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff7407666 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x5555556296e0, timeout=<optimized out>, context=0x5555556275d0) at ../../../glib/gmain.c:4518
#2  g_main_context_iterate.constprop.0 (context=0x5555556275d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4208
#3  0x00007ffff73b22b3 in g_main_loop_run (loop=0x5555556276c0) at ../../../glib/gmain.c:4413
#4  0x00007ffff760c04a in gdbus_shared_thread_func (user_data=0x55555561b070) at ../../../gio/gdbusprivate.c:282
#5  0x00007ffff73e1a51 in g_thread_proxy (data=0x555555620460) at ../../../glib/gthread.c:827
#6  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#7  0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7ffff5673640 (LWP 8277) "gmain"):
#0  0x00007ffff7888d7f in __GI___poll (fds=0x5555556173c0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff7407666 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x5555556173c0, timeout=<optimized out>, context=0x5555556172a0) at ../../../glib/gmain.c:4518
#2  g_main_context_iterate.constprop.0 (context=context@entry=0x5555556172a0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4208
#3  0x00007ffff73b03e3 in g_main_context_iteration (context=0x5555556172a0, may_block=may_block@entry=1) at ../../../glib/gmain.c:4278
#4  0x00007ffff73b0431 in glib_worker_main (data=<optimized out>) at ../../../glib/gmain.c:6180
#5  0x00007ffff73e1a51 in g_thread_proxy (data=0x555555592f60) at ../../../glib/gthread.c:827
#6  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#7  0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 3 (Thread 0x7ffff608e640 (LWP 8276) "mir_demo_se-ust"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff70de136 in lttng_ust_futex (val3=0, uaddr2=0x0, timeout=0x0, val=0, op=0, uaddr=<optimized out>) at ../../../src/lib/lttng-ust/futex.h:56
#2  lttng_ust_futex_async (op=0, val=0, timeout=0x0, uaddr2=0x0, val3=0, uaddr=<optimized out>) at ../../../src/lib/lttng-ust/futex.h:88
#3  wait_for_sessiond (sock_info=0x7ffff7138520 <local_apps.lto_priv>) at /build/ust-mcQuet/ust-2.13.1/src/lib/lttng-ust/lttng-ust-comm.c:1741
#4  ust_listener_thread (arg=0x7ffff7138520 <local_apps.lto_priv>) at /build/ust-mcQuet/ust-2.13.1/src/lib/lttng-ust/lttng-ust-comm.c:1803
#5  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7ffff688f640 (LWP 8275) "mir_demo_se-ust"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff70de136 in lttng_ust_futex (val3=0, uaddr2=0x0, timeout=0x0, val=0, op=0, uaddr=<optimized out>) at ../../../src/lib/lttng-ust/futex.h:56
#2  lttng_ust_futex_async (op=0, val=0, timeout=0x0, uaddr2=0x0, val3=0, uaddr=<optimized out>) at ../../../src/lib/lttng-ust/futex.h:88
#3  wait_for_sessiond (sock_info=0x7ffff713a580 <global_apps.lto_priv>) at /build/ust-mcQuet/ust-2.13.1/src/lib/lttng-ust/lttng-ust-comm.c:1741
#4  ust_listener_thread (arg=0x7ffff713a580 <global_apps.lto_priv>) at /build/ust-mcQuet/ust-2.13.1/src/lib/lttng-ust/lttng-ust-comm.c:1803
#5  0x00007ffff7804b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff7896a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7ffff689a700 (LWP 8271) "mir_demo_server"):
#0  0x00007ffff7888d7f in __GI___poll (fds=0x555555746d60, nfds=2, timeout=967) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff7407666 in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x555555746d60, timeout=<optimized out>, context=0x555555630960) at ../../../glib/gmain.c:4518
#2  g_main_context_iterate.constprop.0 (context=context@entry=0x555555630960, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4208
#3  0x00007ffff73b03e3 in g_main_context_iteration (context=0x555555630960, may_block=1) at ../../../glib/gmain.c:4278
#4  0x00007ffff7d2d6d9 in mir::GLibMainLoop::run (this=0x55555561e880) at ./src/server/glib_main_loop.cpp:120
#5  0x00007ffff7d335c7 in mir::DisplayServer::run (this=0x7fffffffdd10) at ./src/server/display_server.cpp:241
#6  mir::run_mir(mir::ServerConfiguration&, std::function<void (mir::DisplayServer&)>, std::function<void (int)> const&) (config=..., init=..., terminator_=...) at ./src/server/run_mir.cpp:281
#7  0x00007ffff7d3eda7 in mir::Server::run (this=0x5555555fcd40) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#8  0x00007ffff7f4aa12 in miral::MirRunner::Self::run_with(std::initializer_list<std::function<void (mir::Server&)> >) (options=..., this=0x5555555fa4c0) at ./src/miral/runner.cpp:167
#9  miral::MirRunner::run_with(std::initializer_list<std::function<void (mir::Server&)> >) (this=this@entry=0x7fffffffe178, options=...) at ./src/miral/runner.cpp:238
#10 0x000055555555cc18 in main (argc=<optimized out>, argv=<optimized out>) at ./examples/mir_demo_server/server_example.cpp:129
```
</details>
