### ISSUE TITLE
Occasional abort when exiting

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2799]
```
!!! Fatal signal received. Attempting cleanup, but deadlock may occur
Mir fatal error: Unsupported attempt to continue after a fatal signal: SIGSEGV
!!! Fatal signal received. Attempting cleanup, but deadlock may occur
Mir fatal error: Unsupported attempt to continue after a fatal signal: SIGABRT
error in client communication (pid 64065)
[2023-01-20 10:03:42.940075] < - debug - > miral: Restoring sigmask
wl_registry@2: error 0: invalid version for global wl_output (23): have 3, wanted 4
[2023-01-20 10:03:43.034] [info] Using configuration file /home/alan/.config/waybar/config
[2023-01-20 10:03:43.035] [info] Using CSS file /home/alan/.config/waybar/style.css
[2023-01-20 10:03:43.180] [info] Bar configured (width: 2560, height: 30) for output: OUT-1
ERROR: ../src/src/main.c: 527: Failed to bind to address
^C[2023-01-20 10:03:47.207706] < - debug - > mirserver: Handling Interrupt from pid=0
[2023-01-20 10:03:47.208031] <information> xwayland: XWayland stopped
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

**Comment by AlanGriffiths** [comment]
Looks like we're polling something that goes AWOL:
```
(gdb) bt
#0  0x00007ffff771112f in __GI___poll (fds=0x555556197d30, nfds=4, timeout=587851)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6d7133e in g_main_context_poll
    (priority=<optimised out>, n_fds=4, fds=0x555556197d30, timeout=<optimised out>, context=0x55555561d590) at ../../../glib/gmain.c:4543
#2  g_main_context_iterate.constprop.0
    (context=0x55555561d590, block=<optimised out>, dispatch=1, self=<optimised out>)
    at ../../../glib/gmain.c:4233
#3  0x00007ffff6d19d20 in g_main_context_iteration (context=0x55555561d590, may_block=1)
    at ../../../glib/gmain.c:4303
#4  0x00007ffff6eacea7 in mir::GLibMainLoop::run() (this=0x555555619490)
    at /home/alan/display_server/mir1/src/server/glib_main_loop.cpp:142
#5  0x00007ffff6e94620 in mir::DisplayServer::run() (this=0x7fffffffda30)
    at /home/alan/display_server/mir1/src/server/display_server.cpp:239
#6  0x00007ffff6e8aada in mir::run_mir(mir::ServerConfiguration&, std::function<void (mir::DisplayServer&)>, std::function<void (int)> const&) (config=..., init=..., terminator_=...)
    at /home/alan/display_server/mir1/src/server/run_mir.cpp:281
#7  0x00007ffff6ec96ec in mir::Server::run() (this=0x555555610400)
    at /home/alan/display_server/mir1/src/server/server.cpp:408
#8  0x00007ffff7e7f667 in miral::MirRunner::Self::run_with(std::initializer_list<std::function<void (mir::Server&)> >) (this=0x55555560e3d0, options=std::initializer_list of length 13 = {...})
    at /home/alan/display_server/mir1/src/miral/runner.cpp:167
#9  0x00007ffff7e7fe11 in miral::MirRunner::run_with(std::initializer_list<std::function<void (mir::Server&)> >) (this=0x7fffffffdd18, options=std::initializer_list of length 13 = {...})
    at /home/alan/display_server/mir1/src/miral/runner.cpp:238
#10 0x000055555555d7af in main(int, char const**) (argc=2, argv=0x7fffffffe3e8)
    at /home/alan/CLionProjects/Miriway/miriway.cpp:220
```

**Comment by AlanGriffiths** [comment]
A similar Frame log:
```plain
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.819463] < - debug - > mirserver: Handling Terminated from pid=1
2023-01-26T13:59:22Z systemd[1]: Stopping Service for snap application ubuntu-frame.daemon...
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: !!! Fatal signal received. Attempting cleanup, but deadlock may occur
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.820320] <information> evdev-input: Added /dev/input/event2
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.825047] < - ERROR - > gbm-kms: Failed to set DRM CRTC. Screen contents may be incomplete. Try plugging the monitor in again.
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.825726] <information> evdev-input: Added /dev/input/event9
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.828708] <information> evdev-input: Added /dev/input/event0
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.828813] <information> evdev-input: Added /dev/input/event1
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.831682] <information> evdev-input: Added /dev/input/event11
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.831785] <information> evdev-input: Added /dev/input/event12
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.831867] <information> evdev-input: Added /dev/input/event13
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.831940] <information> evdev-input: Added /dev/input/event14
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.832006] <information> evdev-input: Added /dev/input/event15
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.832071] <information> evdev-input: Added /dev/input/event5: Integrated Camera
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.835083] <information> evdev-input: Added /dev/input/event7
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.835187] <information> evdev-input: Added /dev/input/event8
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.835268] <information> evdev-input: Added /dev/input/event6
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.835676] <information> evdev-input: Added /dev/input/event10
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.835761] <information> evdev-input: Added /dev/input/event3
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: [2023-01-26 13:59:22.838641] <information> evdev-input: Added /dev/input/event4
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: Mir fatal error: Unsupported attempt to continue after a fatal signal: SIGSEGV
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: !!! Fatal signal received. Attempting cleanup, but deadlock may occur
2023-01-26T13:59:22Z ubuntu-frame.daemon[373728]: Mir fatal error: Unsupported attempt to continue after a fatal signal: SIGABRT
2023-01-26T13:59:23Z systemd[1]: snap.ubuntu-frame.daemon.service: Main process exited, code=dumped, status=6/ABRT
2023-01-26T13:59:23Z systemd[1]: snap.ubuntu-frame.daemon.service: Failed with result 'core-dump'.
2023-01-26T13:59:23Z systemd[1]: Stopped Service for snap application ubuntu-frame.daemon.
2023-01-26T13:59:23Z systemd[1]: Started Service for snap application ubuntu-frame.daemon.
```

**Comment by wmww** [comment]
Hmm I'm no longer seeing this, even when I run an old Mir. Dozens of runs through the integration tests, hundreds of individual runs of Mir and no repro.

**Comment by Saviq** [comment]
Egmde in the mir-ci tests do still fail some 10% of the time:
```
FAILED test_apps_can_run.py::TestAppsCanRun::test_app_can_run_0_egmde - RuntimeError: egmde closed with exit code -15
FAILED test_apps_can_run.py::TestAppsCanRun::test_app_can_run_2_egmde - RuntimeError: egmde closed with exit code -11
```

https://github.com/MirServer/mir-ci/actions/runs/4264568386/jobs/7733055679

You can restart the job, enable debug logging:
![obraz](https://user-images.githubusercontent.com/231077/224920487-280b44d5-550e-43b5-868c-38541b0544b1.png)

And it will set up an upterm session that you can ssh into, details dropped in the "Setup upterm session" step.
