### ISSUE TITLE
Monitor unplug crashes the server

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#587]
I'm not yet sure exactly what is needed to reproduce (as small variations don't lead to a crash).

Pre-req: `sudo apt install mir-demos mir-graphics-drivers-desktop`

Sign on VT4

1. With a monitor attached: `miral-desktop -kiosk -launcher mir_demo_client_multiwin`
3. Unplug monitor

Expect: Mir continue to run
Actual: Mir crashes

This happens with ppa:mir-team/release and ppa:mir-team/dev

**Comment by AlanGriffiths** [comment]
```
(gdb) bt
#0  0x00007f24b627235b in mir::graphics::mesa::RealKMSOutput::max_refresh_rate() const (this=0x557d9ed9c510)
    at /home/alan/mir/src/platforms/mesa/server/kms/real_kms_output.cpp:152
#1  0x00007f24b6257afd in mir::graphics::mesa::DisplayBuffer::post() (this=0x557d9eea0c10)
    at /home/alan/mir/src/platforms/mesa/server/kms/display_buffer.cpp:734
#2  0x00007f24bd1b0a82 in mir::compositor::CompositingFunctor::operator()() (this=0x557d9eef3560)
    at /home/alan/mir/src/server/compositor/multi_threaded_compositor.cpp:143
#3  0x00007f24bd1b65cd in std::__invoke_impl<void, mir::compositor::CompositingFunctor&>(std::__invoke_other, mir::compositor::CompositingFunctor&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#4  0x00007f24bd1b5b70 in std::__invoke<mir::compositor::CompositingFunctor&>(mir::compositor::CompositingFunctor&) (__fn=...)
    at /usr/include/c++/7/bits/invoke.h:95
#5  0x00007f24bd1b4d9c in std::reference_wrapper<mir::compositor::CompositingFunctor>::operator()<>() const (this=0x7f24b2271b70)
    at /usr/include/c++/7/bits/refwrap.h:356
#6  0x00007f24bd1b3d68 in std::_Function_handler<void (), std::reference_wrapper<mir::compositor::CompositingFunctor> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#7  0x00007f24bd04cc56 in std::function<void ()>::operator()() const (this=0x7f24b2271b70) at /usr/include/c++/7/bits/std_function.h:706
#8  0x00007f24bd3835a5 in (anonymous namespace)::Task::execute() (this=0x7f24b2271b70) at /home/alan/mir/src/server/thread/basic_thread_pool.cpp:40
#9  0x00007f24bd383900 in (anonymous namespace)::Worker::operator()() (this=0x557d9ef0ee40) at /home/alan/mir/src/server/thread/basic_thread_pool.cpp:91
#10 0x00007f24bd386323 in std::__invoke_impl<void, (anonymous namespace)::Worker&>(std::__invoke_other, (anonymous namespace)::Worker&) (__f=...)
    at /usr/include/c++/7/bits/invoke.h:60
#11 0x00007f24bd385db4 in std::__invoke<(anonymous namespace)::Worker&>((anonymous namespace)::Worker&) (__fn=...)
    at /usr/include/c++/7/bits/invoke.h:95
#12 0x00007f24bd38554a in std::reference_wrapper<(anonymous namespace)::Worker>::operator()<>(void) const (this=0x557d9ed10688)
    at /usr/include/c++/7/bits/refwrap.h:356
#13 0x00007f24bd384b99 in std::__invoke_impl<void, std::reference_wrapper<(anonymous namespace)::Worker> >(std::__invoke_other, std::reference_wrapper<(anonymous namespace)::Worker>&&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#14 0x00007f24bd38455c in std::__invoke<std::reference_wrapper<(anonymous namespace)::Worker> >(std::reference_wrapper<(anonymous namespace)::Worker>&&) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#15 0x00007f24bd3867ca in std::thread::_Invoker<std::tuple<std::reference_wrapper<(anonymous namespace)::Worker> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x557d9ed10688) at /usr/include/c++/7/thread:234
#16 0x00007f24bd386786 in std::thread::_Invoker<std::tuple<std::reference_wrapper<(anonymous namespace)::Worker> > >::operator()() (this=0x557d9ed10688)
    at /usr/include/c++/7/thread:243
#17 0x00007f24bd386756 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::reference_wrapper<(anonymous namespace)::Worker> > > >::_M_run() (this=0x557d9ed10680) at /usr/include/c++/7/thread:186
#18 0x00007f24bdf40733 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007f24bda526db in start_thread (arg=0x7f24b2272700) at pthread_create.c:463
#20 0x00007f24bd77b88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:9
```

**Comment by AlanGriffiths** [comment]
OK, I can also reproduce with a Wayland client (glmark2-es2-wayland) so this shouldn't be ignored.
