### ISSUE TITLE
Mir with eglstreams crashes on shutdown

### ISSUE THREAD

**Issue by gerboland** [MirServer/mir#858]
I have mir-test-tools deb and snap installed on a Bionic system with nvidia 430 driver. Running

    SNAP=/snap/mir-test-tools/current/ gdb --arg mir_demo_server --test-client /snap/mir-test-tools/current/qml/spinning-rect.sh

Mir shuts down with a crash. 

```
[2019-06-07 15:42:39.948940] <information> mirserver: Starting
[2019-06-07 15:42:39.951208] < - debug - > mirserver: Not using logind for session management: Seat has no active session
[2019-06-07 15:42:39.951461] < - debug - > mirserver: Using Linux VT subsystem for session management
[2019-06-07 15:42:39.951512] <information> mircommon: Loading modules from: /usr/lib/x86_64-linux-gnu/mir/server-platform
[2019-06-07 15:42:39.951546] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-mesa-kms.so.16
[2019-06-07 15:42:39.951557] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/server-mesa-x11.so.16
[2019-06-07 15:42:39.951564] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-eglstream-kms.so.16
[2019-06-07 15:42:39.951572] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/input-evdev.so.7
[2019-06-07 15:42:39.952241] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/input-stub.so
[2019-06-07 15:42:39.952386] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-dummy.so
[2019-06-07 15:42:39.954744] <information> mesa-kms: EGL platform does not support EGL_KHR_platform_gbm extension
[2019-06-07 15:42:39.991979] <information> mesa-kms: Detected software renderer: llvmpipe (LLVM 7.0, 256 bits)
[2019-06-07 15:42:40.004991] <information> mirplatform: Found graphics driver: mir:mesa-kms (version 1.2.0) Support priority: 128
[2019-06-07 15:42:40.005014] <information> mirplatform: Found graphics driver: mir:mesa-x11 (version 1.2.0) Support priority: 0
[2019-06-07 15:42:40.005070] < - debug - > eglstream: Found EGLDeviceEXT with device extensions: EGL_NV_device_cuda EGL_EXT_device_drm
[2019-06-07 15:42:40.056018] <information> mirplatform: Found graphics driver: mir:eglstream-kms (version 1.2.0) Support priority: 256
[2019-06-07 15:42:40.056081] <information> mirplatform: Found graphics driver: mir:stub-graphics (version 1.2.0) Support priority: 1
[2019-06-07 15:42:40.056224] <information> mirserver: Selected driver: mir:eglstream-kms (version 1.2.0)
[2019-06-07 15:42:40.194419] <information> mirserver: Using software cursor
[2019-06-07 15:42:40.195246] <information> mircommon: Loading modules from: /usr/lib/x86_64-linux-gnu/mir/server-platform
[2019-06-07 15:42:40.195297] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-mesa-kms.so.16
[2019-06-07 15:42:40.195314] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/server-mesa-x11.so.16
[2019-06-07 15:42:40.195322] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-eglstream-kms.so.16
[2019-06-07 15:42:40.195333] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/input-evdev.so.7
[2019-06-07 15:42:40.221344] <information> mirserver: Selected input driver: mir:evdev-input (version: 1.2.0)
[2019-06-07 15:42:40.225080] < -warning- > Wayland: Failed to bind Wayland EGL display. Accelerated EGL will be unavailable.: /build/mir-xw5crR/mir-1.2.0+dev50-g34a96a69ce/src/platforms/eglstream-kms/server/buffer_allocator.cpp(405): Throw in function virtual void mir::graphics::eglstream::BufferAllocator::bind_display(wl_display*, std::shared_ptr<mir::Executor>)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::system_error> >
std::exception::what: Failed to bind Wayland EGL display: EGL_SUCCESS (0x3000)

error: XDG_RUNTIME_DIR not set in the environment
[2019-06-07 15:42:40.226055] <information> mirserver: Mir version 1.2.0
[2019-06-07 15:42:40.226124] <information> mir::examples: Starting test client: /snap/mir-test-tools/current/qml/spinning-rect.sh
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
error: XDG_RUNTIME_DIR not set in the environment.
Failed to create display (No such file or directory)
[2019-06-07 15:42:40.233114] <information> GLRenderer: EGL vendor: NVIDIA
[2019-06-07 15:42:40.233154] <information> GLRenderer: EGL version: 1.5
[2019-06-07 15:42:40.233160] <information> GLRenderer: EGL client APIs: OpenGL_ES OpenGL
[2019-06-07 15:42:40.233166] <information> GLRenderer: GL vendor: NVIDIA Corporation
[2019-06-07 15:42:40.233169] <information> GLRenderer: GL renderer: GeForce GTX 1070/PCIe/SSE2
[2019-06-07 15:42:40.233173] <information> GLRenderer: GL version: OpenGL ES 3.2 NVIDIA 430.14
[2019-06-07 15:42:40.233176] <information> GLRenderer: GLSL version: OpenGL ES GLSL ES 3.20
[2019-06-07 15:42:40.233222] <information> GLRenderer: GL max texture size = 32768
[2019-06-07 15:42:40.233229] <information> GLRenderer: GL framebuffer bits: RGBA=8880, depth=0, stencil=0
[2019-06-07 15:42:40.240362] <information> mirserver: Initial display configuration:
[2019-06-07 15:42:40.240379] <information> mirserver: * Output 43: DVI-D disconnected
[2019-06-07 15:42:40.240385] <information> mirserver: * Output 45: HDMI-A connected, used
[2019-06-07 15:42:40.240392] <information> mirserver: . |_ Physical size 18.5" 410x230mm
[2019-06-07 15:42:40.240396] <information> mirserver: . |_ Power is on
[2019-06-07 15:42:40.240400] <information> mirserver: . |_ Current mode 1280x1024 75.02Hz
[2019-06-07 15:42:40.240403] <information> mirserver: . |_ Orientation normal
[2019-06-07 15:42:40.240431] <information> mirserver: . |_ Logical size 1280x1024
[2019-06-07 15:42:40.240435] <information> mirserver: . |_ Logical position +0+0
[2019-06-07 15:42:40.240439] <information> mirserver: . |_ Scaling factor: 1.00
[2019-06-07 15:42:40.240442] <information> mirserver: * Output 47: DisplayPort disconnected
[2019-06-07 15:42:40.240446] <information> mirserver: * Output 50: DisplayPort disconnected
[2019-06-07 15:42:40.240449] <information> mirserver: * Output 53: DisplayPort disconnected
[2019-06-07 15:42:51.226670] <information> server_example_test_client.cpp: Client has exited with status 255
[2019-06-07 15:42:51.226727] <information> mirserver: Stopping
terminate called without an active exception
Aborted (core dumped)
```
That Wayland complaint doesn't appear to be critical.

Backtrace is
```
terminate called without an active exception

Thread 1 "mir_demo_server" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff69dde97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff69df801 in __GI_abort () at abort.c:79
#2  0x00007ffff7253957 in __gnu_cxx::__verbose_terminate_handler() () at ../../../../src/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff7259ab6 in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at ../../../../src/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff7259af1 in std::terminate() () at ../../../../src/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007fffee51a3f4 in std::_Sp_counted_ptr_inplace<mir::graphics::eglstream::kms::EGLOutput, std::allocator<mir::graphics::eglstream::kms::EGLOutput>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (this=0x5555556a12e0) at /usr/include/c++/7/bits/shared_ptr_base.h:533
#6  0x00007fffee509f0a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x5555556a12e0) at /usr/include/c++/7/bits/shared_ptr_base.h:154
#7  0x00007fffee509f0a in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() () at /usr/include/c++/7/bits/shared_ptr_base.h:684
#8  0x00007fffee509f0a in std::__shared_ptr<mir::graphics::eglstream::kms::EGLOutput, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() () at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#9  0x00007fffee509f0a in std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>::~shared_ptr() () at /usr/include/c++/7/bits/shared_ptr.h:93
#10 0x00007fffee509f0a in std::_Destroy<std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput> >(std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*) ()
    at /usr/include/c++/7/bits/stl_construct.h:98
#11 0x00007fffee509f0a in std::_Destroy_aux<false>::__destroy<std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*>(std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*, std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*) () at /usr/include/c++/7/bits/stl_construct.h:108
#12 0x00007fffee509f0a in std::_Destroy<std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*>(std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*, std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*) () at /usr/include/c++/7/bits/stl_construct.h:137
#13 0x00007fffee509f0a in std::_Destroy<std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*, std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput> >(std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*, std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput>*, std::allocator<std::shared_ptr<mir::graphics::eglstream::kms::EGLOutput> >&) ()
    at /usr/include/c++/7/bits/stl_construct.h:206
#14 0x00007fffee509f0a in __base_dtor  (this=0x555555726838) at /usr/include/c++/7/bits/stl_vector.h:434
#15 0x00007fffee509f0a in __base_dtor  () at ./src/platforms/eglstream-kms/server/kms_display_configuration.h:36
#16 0x00007fffee509f0a in __base_dtor  (this=0x5555557267b0) at ./src/platforms/eglstream-kms/server/display.h:41
#17 0x00007fffee509f59 in __deleting_dtor  (this=0x5555557267b0) at ./src/platforms/eglstream-kms/server/display.h:41
#18 0x00007ffff78ccb86 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x5555557005a0) at /usr/include/c++/7/bits/shared_ptr_base.h:154
#19 0x00007ffff78ccd76 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() () at /usr/include/c++/7/bits/shared_ptr_base.h:684
#20 0x00007ffff78ccd76 in std::__shared_ptr<mir::graphics::Display, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() () at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#21 0x00007ffff78ccd76 in std::shared_ptr<mir::graphics::Display>::~shared_ptr() () at /usr/include/c++/7/bits/shared_ptr.h:93
#22 0x00007ffff78ccd76 in __base_dtor  (this=0x5555555e9960) at ./src/server/display_server.cpp:48
#23 0x00007ffff78ccd76 in __base_dtor  (this=<optimized out>) at ./src/server/display_server.cpp:226
#24 0x00007ffff78d1291 in mir::run_mir(mir::ServerConfiguration&, std::function<void (mir::DisplayServer&)>, std::function<void (int)> const&) (config=..., init=..., terminator=...)
    at ./src/server/run_mir.cpp:98
#25 0x00007ffff77e3105 in mir::Server::run() (this=0x5555555e2510) at ./src/server/server.cpp:412
#26 0x00007ffff7f6898c in  () at /usr/lib/x86_64-linux-gnu/libmiral.so.3
#27 0x00005555555600a3 in main ()
```

**Comment by RAOF** [comment]
Is this fixed?

**Comment by AlanGriffiths** [comment]
It is
